from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'game/unity/Assets/Game/Scripts'
def edit(file,old,new):
 p=BASE/file;t=p.read_text(encoding='utf-8-sig')
 if new in t:return
 assert old in t,(file,old)
 p.write_text(t.replace(old,new),encoding='utf8')
edit('Core/EnemyCombatStatus.cs','public int FireVulnerabilityPercent','public int IgnitionFlags {get;private set;}\n        public bool AddIgnition(){if(++IgnitionFlags<3)return false;IgnitionFlags=0;return true;}\n        public int FireVulnerabilityPercent')
edit('Core/EnemyCombatStatus.cs','FireVulnerabilityPercent=FireVulnerabilityTurns=0;}','FireVulnerabilityPercent=FireVulnerabilityTurns=IgnitionFlags=0;}')
edit('Core/EnemyCombatStatus.cs','public string Description =>','public string Description => (IgnitionFlags>0?"IGNITION "+IgnitionFlags+"/3 / ":"")+')
edit('Core/TimedSelfEffects.cs','kind!="fire-amplification" &&','kind!="speed" && kind!="fire-amplification" &&')
edit('Core/TimedSelfEffects.cs','public static string Label(string kind) =>','public static string Label(string kind) => kind=="speed"?"速度＋":')
edit('Core/TimedSelfEffects.cs','public int FireAmplificationPercent','public int TimedSpeedPercent=>EffectPercent("speed");\n        public int FireAmplificationPercent')
edit('Core/BattleState.cs','100+JobAllStatsPercent+JobSpeedPercent','100+JobAllStatsPercent+JobSpeedPercent+TimedSpeedPercent')
edit('Core/CombatDefinitionCatalog.cs','public int criticalBonusBp,damageCap;','public int criticalBonusBp,damageCap;\n        public int chainChanceBonusBp;')
edit('Core/CombatDefinitionCatalog.cs','if(skills.Any(s=>s.enemyFireVulnerabilityPercent','if(skills.Any(s=>s.chainChanceBonusBp<0 || s.chainChanceBonusBp>1500 || s.chainChanceBonusBp>0 && s.effectRuleId!="effect.damage"))throw new ArgumentException("Invalid authored chain bonus.");\n            if(skills.Any(s=>s.enemyFireVulnerabilityPercent')
for f in ['Core/HeroineSkillRules.cs','Core/PlayableBattle.cs']:
 edit(f,'criticalBonusBp=s.criticalBonusBp,','criticalBonusBp=s.criticalBonusBp,chainChanceBonusBp=s.chainChanceBonusBp,')
edit('Core/HeroineSkillRules.cs','if(s.criticalBonusBp>0)','if(s.chainChanceBonusBp>0)result+="自動チェイン接続率＋"+(s.chainChanceBonusBp/100f).ToString("0.#")+"%。";\n            if(s.criticalBonusBp>0)')
edit('Core/AutomaticChain.cs','Action<int,bool,int> execute)','Action<int,bool,int> execute,bool authoredBonus=false)')
edit('Core/AutomaticChain.cs','(skillBonusBp!=0 && skillBonusBp!=1000)','(authoredBonus?skillBonusBp<0 || skillBonusBp>2500:skillBonusBp!=0 && skillBonusBp!=1000)')
edit('Core/PlayableBattleChain.cs','var outcome=AutomaticChain.Resolve(origin,5,skillBonus,marked','int authoredBonus=activeChainBonusBp;\n            var outcome=AutomaticChain.Resolve(origin,5,skillBonus+authoredBonus,marked')
edit('Core/PlayableBattleChain.cs','                });\n            Chain=outcome.Participants;','                },authoredBonus:authoredBonus>0);\n            Chain=outcome.Participants;')
edit('Core/PlayableBattleChain.cs','private int[] skillChainBonuses','private int activeChainBonusBp;\n        private int[] skillChainBonuses')
edit('Core/PlayableBattle.cs','if(UsesTimeline && ChainEligible(heroIndex,skill)) ResolveAutomaticChain(heroIndex,skillChainBonuses[skill],(bool[])cumulativeChainActors.Clone());','if(UsesTimeline && ChainEligible(heroIndex,skill)){activeChainBonusBp=commandDefinitions?[heroIndex,skill].chainChanceBonusBp??0;ResolveAutomaticChain(heroIndex,skillChainBonuses[skill],(bool[])cumulativeChainActors.Clone());activeChainBonusBp=0;}')
edit('Core/PlayableBattleJobRules.cs','public int Gauge {','public int Gear {get;internal set;}=1;\n        public int NitroCount {get;internal set;}\n        public bool NitroSelected {get;internal set;}\n        public int ChaserRecoveryPercent {get;internal set;}=100;\n        public int Gauge {')
edit('Core/PlayableBattleJobRules.cs','if(Job(actor,"alchemist"))return','if(Job(actor,"chaser"))return "駆動 "+h.JobResource+"/"+h.JobResourceMax+" ／ GEAR "+j.Gear+" ／ NITRO "+j.NitroCount+"/10"+(j.NitroSelected?"・次回WT0":"");\n            if(Job(actor,"alchemist"))return')
edit('Core/PlayableBattleJobRules.cs','if(Job(actor,"healer"))return commandDefinitions','if(Job(actor,"chaser"))return jobStates[actor].NitroSelected?0:ChaserGearCost(jobStates[actor].Gear);\n            if(Job(actor,"healer"))return commandDefinitions')
edit('Core/PlayableBattleJobRules.cs','!RequiresPanzerDefense(actor) &&','!RequiresPanzerDefense(actor) && ChaserCommandValid(actor) &&')
edit('Core/PlayableBattleJobRules.cs','if(!UsesJobRulesV2)return;var j=jobStates[actor];','if(!UsesJobRulesV2)return;var j=jobStates[actor];CommitChaserGear(actor,cost);')
edit('Core/PlayableBattleJobRules.cs','if(next==boundary){TickSongs();','if(next==boundary){TickChaserResources();TickSongs();')
edit('Core/PlayableBattle.cs','JobAttackReaction(actor);\n            var d=','JobAttackReaction(actor);ChaserIgnition(actor,alchemyHitTargets);\n            var d=')
edit('Core/PlayableBattleChain.cs','targetIds:effect.TargetIds);','targetIds:effect.TargetIds);\n                    if(effect.TargetIds.Count>0 && def.Effect==ChainEffect.Damage)ChaserIgnition(actor,effect.TargetIds);')
edit('Core/PlayableBattleTiming.cs','public long RecoveryDelay(int actor,int slot) => SkillTimingDefinition.Delay(State.Heroes[actor].Speed,Timing(actor,slot).RecoveryPercent);','public long RecoveryDelay(int actor,int slot) => Job(actor,"chaser")?ChaserDelay(SkillTimingDefinition.Delay(State.Heroes[actor].Speed,Timing(actor,slot).RecoveryPercent),ChaserSelectedRecovery(actor)):SkillTimingDefinition.Delay(State.Heroes[actor].Speed,Timing(actor,slot).RecoveryPercent);')
edit('Core/PlayableBattle.cs','Math.Max(1,RecoveryDelay(actor,slot)*(100-(commandDefinitions?[actor,slot].selfWaitReductionPercent??0))/100)','Job(actor,"chaser")?ChaserDelay(SkillTimingDefinition.Delay(State.Heroes[actor].Speed,Timing(actor,slot).RecoveryPercent),jobStates[actor].ChaserRecoveryPercent):Math.Max(1,RecoveryDelay(actor,slot)*(100-(commandDefinitions?[actor,slot].selfWaitReductionPercent??0))/100)')
edit('Core/PlayableBattle.cs','(IsAttackSkill(heroIndex,skill)?CommandRecoveryDelay','(IsAttackSkill(heroIndex,skill) || Job(heroIndex,"chaser")?CommandRecoveryDelay')
edit('Core/PlayableBattleTiming.cs','Clock+RecoveryDelay(actor,0)+wait;RecordPresentation','Clock+SkillTimingDefinition.Delay(h.Speed,Timing(actor,0).RecoveryPercent)+wait;RecordPresentation')
edit('Core/CombatDefinitionCatalog.cs','id.StartsWith("heroine.annihilator",StringComparison.Ordinal)?Enumerable.Range','(id.StartsWith("heroine.annihilator",StringComparison.Ordinal) || id=="heroine.nighthawk")?Enumerable.Range')
edit('Data/HeroineIdentityCatalog.cs','id=="job.alchemist"?"アルケミスト":','id=="job.alchemist"?"アルケミスト":id=="job.chaser"?"チェイサー":')
edit('Data/HeroineIdentityCatalog.cs','default:throw','case "heroine.nighthawk":name="夜道を照らす灯り";master="隣を歩く勇気";icon="star";bonus="会心率＋5%";break;\n                default:throw')
edit('Data/HeroineIdentityCatalog.cs','string resource=job=="job.alchemist"','string resource=job=="job.chaser"?"駆動は毎Battle Turn＋2。GEAR2/3は2/4消費・NITRO＋1。5で次スキルWT0。対象Flag3で全体IGNITION。":job=="job.alchemist"')
edit('Core/HeroineTraitRules.cs','job=="job.fighter" && stat=="critical"','(job=="job.fighter" || job=="job.chaser") && stat=="critical"')
edit('Core/HeroineSkillRules.cs','string resource=job.id=="job.alchemist"','string resource=job.id=="job.chaser"?"毎Battle Turnに駆動＋2。GEAR2/3で待機短縮、NITRO5で次スキルWT0、対象Flag3で全体攻撃":job.id=="job.alchemist"')
for f in ['Core/PlayableBattle.cs','Presentation/HeroineSanctuaryView.cs']:
 edit(f,'=="heroine.oriflamme")','=="heroine.oriflamme" || '+('formationIds[i]' if f.startswith('Core') else 'id')+'=="heroine.nighthawk")')
edit('Presentation/HeroineSanctuaryArt.cs','hero=="heroine.oriflamme")','hero=="heroine.oriflamme" || hero=="heroine.nighthawk")')
edit('Data/ProductionEconomyCatalog.cs','"明日を灯す炎"};','"明日を灯す炎","星図の指針","青い羽根の盾","夜明けの足音"};')
edit('Data/ProductionEconomyCatalog.cs','10,6,16};','10,6,16,8,6,14};')
edit('Data/ProductionEconomyCatalog.cs','1.2f,1.12f,1.4f};','1.2f,1.12f,1.4f,1.18f,1.14f,1.38f};')
edit('Data/ProductionEconomyCatalog.cs','"炎翼"};','"炎翼","夜星"};')
edit('Data/ProductionEconomyCatalog.cs','private static readonly string[] BranchNames','private static readonly string[] WeaponOwners={"heroine.slayer","heroine.iconoclast","heroine.undermine","heroine.echidna","heroine.excalipan","heroine.r","heroine.annihilator","heroine.annihilator-holy","heroine.shell","heroine.oriflamme","heroine.nighthawk"};\n        private static int WeaponOwner(string id){int index=Array.IndexOf(WeaponOwners,id);if(index<0)throw new ArgumentException("Missing authored weapon identity "+id);return index;}\n        private static readonly string[] BranchNames')
for value in ['node.heroineId','heroId','n.heroineId']:
 edit('Data/ProductionEconomyCatalog.cs','Array.IndexOf(combat.HeroineIds,'+value+')','WeaponOwner('+value+')')
edit('Data/ProductionStoryCatalog.cs','Plan10OriflammeHomeArt.Apply(home);','Plan10OriflammeHomeArt.Apply(home);\n            Plan10NighthawkHomeArt.Apply(home);')
art=(BASE/'Data/Plan10OriflammeHomeArt.cs').read_text(encoding='utf8').replace('Plan10OriflammeHomeArt','Plan10NighthawkHomeArt').replace('"oriflamme"','"nighthawk"');(BASE/'Data/Plan10NighthawkHomeArt.cs').write_text(art,encoding='utf8')
edit('Presentation/PrototypeBootstrap.cs','Environment.GetCommandLineArgs().Contains("-captureOriflamme")?','Environment.GetCommandLineArgs().Contains("-captureNighthawk")?"Combat/battle-plan10-nighthawk":Environment.GetCommandLineArgs().Contains("-captureOriflamme")?')
edit('Presentation/PrototypeBootstrap.cs','?"Combat/battle-formal":"Combat/battle-plan10-oriflamme"','?"Combat/battle-formal":"Combat/battle-plan10-nighthawk"')
edit('Presentation/PrototypeBootstrap.cs','PreparePlan10OriflammeCapture(args);','PreparePlan10OriflammeCapture(args);\n            PreparePlan10NighthawkCapture(args);')
edit('Presentation/ProductionStoryExperience.cs','(Environment.GetCommandLineArgs().Contains("-captureOriflamme")','(Environment.GetCommandLineArgs().Contains("-captureNighthawk") || Environment.GetCommandLineArgs().Contains("-captureOriflamme")')
edit('Presentation/ProductionStoryExperience.cs','combatDefinitions.HeroineIds.Contains("heroine.oriflamme")?','combatDefinitions.HeroineIds.Contains("heroine.nighthawk")?"Story/plan10-nighthawk-story-content":combatDefinitions.HeroineIds.Contains("heroine.oriflamme")?')
edit('Presentation/BattleIllustrationView.cs','"shell","oriflamme"','"shell","oriflamme","nighthawk"')
edit('Presentation/AdvExperience.cs','actor.HeroineId=="heroine.oriflamme" ||','actor.HeroineId=="heroine.nighthawk" || actor.HeroineId=="heroine.oriflamme" ||')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','"heroine.shell","heroine.oriflamme"','"heroine.shell","heroine.oriflamme","heroine.nighthawk"')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','GrowthFrame(285,100,1030,700)','GrowthFrame(285,65,1030,780)')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,130','330,95')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,191','330,156')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,264+i*70','330,229+i*70')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,635','330,665')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','970,720','970,765')
edit('Presentation/BattleJobControls.cs','}else if(j.Id=="job.alchemist"){','}else if(j.Id=="job.chaser"){\n                DrawChaserBattleControls(actor,enabled,jobButton);\n            }else if(j.Id=="job.alchemist"){')
edit('Presentation/BattleJobControls.cs','j.Id=="job.healer" || j.Id=="job.alchemist")','j.Id=="job.healer" || j.Id=="job.alchemist" || j.Id=="job.chaser")')
print('Nighthawk connected.')
