from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'game/unity/Assets/Game/Scripts'
def edit(file,old,new):
 p=BASE/file;t=p.read_text(encoding='utf-8-sig')
 if new in t:return
 assert old in t,(file,old)
 p.write_text(t.replace(old,new),encoding='utf8')
edit('Core/PlayableBattleAlchemy.cs','amount:units[0]*20','amount=units[0]*20')
edit('Core/EnemyCombatStatus.cs','public int Meter(string kind)', '''public int FireVulnerabilityPercent {get;private set;}
        public int FireVulnerabilityTurns {get;private set;}
        public void SetFireVulnerability(int percent,int turns){if(percent<1 || percent>100 || turns<1 || turns>10)throw new ArgumentException("Invalid fire vulnerability.");FireVulnerabilityPercent=percent;FireVulnerabilityTurns=turns;}
        public int Meter(string kind)''')
edit('Core/EnemyCombatStatus.cs','public void Tick() {foreach','public void Tick() {if(FireVulnerabilityTurns>0 && --FireVulnerabilityTurns==0)FireVulnerabilityPercent=0;foreach')
edit('Core/EnemyCombatStatus.cs','public void ClearAll(){meter.Clear();duration.Clear();}','public void ClearAll(){meter.Clear();duration.Clear();FireVulnerabilityPercent=FireVulnerabilityTurns=0;}')
edit('Core/EnemyCombatStatus.cs','public string Description => string.Join','public string Description => (FireVulnerabilityTurns>0?"火弱点＋"+FireVulnerabilityPercent+"%（残り"+FireVulnerabilityTurns+"） / ":"")+string.Join')
edit('Core/TimedSelfEffects.cs','kind!="attack" &&','kind!="fire-amplification" && kind!="attack" &&')
edit('Core/TimedSelfEffects.cs','public static string Label(string kind) =>','public static string Label(string kind) => kind=="fire-amplification"?"火増幅＋":')
edit('Core/TimedSelfEffects.cs','public bool ForcedTarget =>','public int FireAmplificationPercent=>EffectPercent("fire-amplification");\n        public bool ForcedTarget =>')
edit('Core/BattleActionResolver.cs','if(battle.ReferenceStatusRules){var status','if(skill.Attributes.Contains("火"))raw*=1m+(hero.FireAmplificationPercent+battle.EnemyStatus(targetId).FireVulnerabilityPercent)/100m;\n            if(battle.ReferenceStatusRules){var status')
edit('Core/CombatDefinitionCatalog.cs','public int targetStatusBonusPercent;','public int targetStatusBonusPercent;\n        public int enemyFireVulnerabilityPercent,enemyFireVulnerabilityTurns,allAlchemistResourceGain;')
edit('Core/CombatDefinitionCatalog.cs','if(skills.Any(s=>s.selfHealingBaseAttackPercent','if(skills.Any(s=>s.enemyFireVulnerabilityPercent<0 || s.enemyFireVulnerabilityPercent>100 || s.enemyFireVulnerabilityTurns<0 || s.enemyFireVulnerabilityTurns>10 || (s.enemyFireVulnerabilityPercent==0)!=(s.enemyFireVulnerabilityTurns==0) || s.allAlchemistResourceGain<0 || s.allAlchemistResourceGain>10))throw new ArgumentException("Invalid alchemy skill effects.");\n            if(skills.Any(s=>s.selfHealingBaseAttackPercent')
for f in ['Core/HeroineSkillRules.cs','Core/PlayableBattle.cs']:
 edit(f,'targetStatusBonusPercent=s.targetStatusBonusPercent,','targetStatusBonusPercent=s.targetStatusBonusPercent,enemyFireVulnerabilityPercent=s.enemyFireVulnerabilityPercent,enemyFireVulnerabilityTurns=s.enemyFireVulnerabilityTurns,allAlchemistResourceGain=s.allAlchemistResourceGain,')
edit('Core/PlayableBattle.cs','GainJobCommandResource(heroIndex);','GainJobCommandResource(heroIndex);\n            if(commandDefinitions!=null && commandDefinitions[heroIndex,skill].allAlchemistResourceGain>0)for(int i=0;i<5;i++)if(Job(i,"alchemist") && State.Heroes[i].IsAlive)State.Heroes[i].GainResource(commandDefinitions[heroIndex,skill].allAlchemistResourceGain);')
edit('Core/PlayableBattle.cs','var d=commandDefinitions[actor,slot];int before=','var d=commandDefinitions[actor,slot];if(d.enemyFireVulnerabilityPercent>0)foreach(string target in LastAttackTargetsForAlchemy(actor,slot))State.EnemyStatus(target).SetFireVulnerability(d.enemyFireVulnerabilityPercent,d.enemyFireVulnerabilityTurns);int before=')
# Resolver already records the actual target list. Apply vulnerability to precisely that list, not a UI selection.
edit('Core/PlayableBattle.cs','LastHealingTargets=outcome.SelfHealing','alchemyHitTargets=outcome.TargetIds.ToArray();\n            LastHealingTargets=outcome.SelfHealing')
edit('Core/PlayableBattleJobRules.cs','if(Job(actor,"panzer"))return','if(Job(actor,"alchemist"))return "錬成 "+h.JobResource+"/"+h.JobResourceMax+" ／ 5属性を投入・行動消費なし";\n            if(Job(actor,"panzer"))return')
edit('Core/PlayableBattleJobRules.cs','if(Job(actor,"blaster") || Job(actor,"healer")','if(Job(actor,"alchemist") || Job(actor,"blaster") || Job(actor,"healer")')
edit('Data/HeroineIdentityCatalog.cs','id=="job.panzer"?"パンツァー":','id=="job.panzer"?"パンツァー":id=="job.alchemist"?"アルケミスト":')
edit('Data/HeroineIdentityCatalog.cs','default:throw','case "heroine.oriflamme":name="消えない正義の火";master="帰るための炎";icon="flame";bonus="攻撃＋5%";break;\n                default:throw')
edit('Data/HeroineIdentityCatalog.cs','string resource=job=="job.panzer"','string resource=job=="job.alchemist"?"錬成資源：通常行動＋1。火・雷・闇・光・斬撃を投入し、READYを消費せず錬成。":job=="job.panzer"')
edit('Core/HeroineTraitRules.cs','job=="job.artist")','job=="job.artist" || job=="job.alchemist")')
edit('Core/HeroineSkillRules.cs','if(s.resourceGain>0)','if(s.enemyFireVulnerabilityPercent>0)result+="対象に火弱点＋"+s.enemyFireVulnerabilityPercent+"%（"+s.enemyFireVulnerabilityTurns+"Battle Turn）。";\n            if(s.allAlchemistResourceGain>0)result+="生存するアルケミスト全員の錬成資源＋"+s.allAlchemistResourceGain+"。";\n            if(s.resourceGain>0)')
edit('Core/HeroineSkillRules.cs','string resource=job.id=="job.panzer"','string resource=job.id=="job.alchemist"?"通常行動で錬成＋1。5属性の錬成はREADYを消費しません":job.id=="job.panzer"')
for f in ['Core/PlayableBattle.cs','Presentation/HeroineSanctuaryView.cs']:
 edit(f,'=="heroine.shell")','=="heroine.shell" || '+('formationIds[i]' if f.startswith('Core') else 'id')+'=="heroine.oriflamme")')
edit('Presentation/HeroineSanctuaryArt.cs','hero=="heroine.shell")','hero=="heroine.shell" || hero=="heroine.oriflamme")')
edit('Data/ProductionEconomyCatalog.cs','"帰還の回転翼"};','"帰還の回転翼","黒剣の火花","五色の触媒","明日を灯す炎"};')
edit('Data/ProductionEconomyCatalog.cs','9,7,14};','9,7,14,10,6,16};')
edit('Data/ProductionEconomyCatalog.cs','1.2f,1.14f,1.36f};','1.2f,1.14f,1.36f,1.2f,1.12f,1.4f};')
edit('Data/ProductionEconomyCatalog.cs','"鋼翼"};','"鋼翼","炎翼"};')
edit('Data/ProductionStoryCatalog.cs','Plan10ShellHomeArt.Apply(home);','Plan10ShellHomeArt.Apply(home);\n            Plan10OriflammeHomeArt.Apply(home);')
art=(BASE/'Data/Plan10ShellHomeArt.cs').read_text(encoding='utf8').replace('Plan10ShellHomeArt','Plan10OriflammeHomeArt').replace('"shell"','"oriflamme"');(BASE/'Data/Plan10OriflammeHomeArt.cs').write_text(art,encoding='utf8')
edit('Presentation/PrototypeBootstrap.cs','Environment.GetCommandLineArgs().Contains("-captureShell")?','Environment.GetCommandLineArgs().Contains("-captureOriflamme")?"Combat/battle-plan10-oriflamme":Environment.GetCommandLineArgs().Contains("-captureShell")?')
edit('Presentation/PrototypeBootstrap.cs','?"Combat/battle-formal":"Combat/battle-plan10-shell"','?"Combat/battle-formal":"Combat/battle-plan10-oriflamme"')
edit('Presentation/PrototypeBootstrap.cs','PreparePlan10ShellCapture(args);','PreparePlan10ShellCapture(args);\n            PreparePlan10OriflammeCapture(args);')
edit('Presentation/ProductionStoryExperience.cs','(Environment.GetCommandLineArgs().Contains("-captureShell")','(Environment.GetCommandLineArgs().Contains("-captureOriflamme") || Environment.GetCommandLineArgs().Contains("-captureShell")')
edit('Presentation/ProductionStoryExperience.cs','combatDefinitions.HeroineIds.Contains("heroine.shell")?','combatDefinitions.HeroineIds.Contains("heroine.oriflamme")?"Story/plan10-oriflamme-story-content":combatDefinitions.HeroineIds.Contains("heroine.shell")?')
edit('Presentation/BattleIllustrationView.cs','"annihilator-holy","shell"','"annihilator-holy","shell","oriflamme"')
edit('Presentation/AdvExperience.cs','actor.HeroineId=="heroine.shell" ||','actor.HeroineId=="heroine.oriflamme" || actor.HeroineId=="heroine.shell" ||')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','"heroine.annihilator-holy","heroine.shell"','"heroine.annihilator-holy","heroine.shell","heroine.oriflamme"')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','GrowthFrame(285,150,1030,590)','GrowthFrame(285,100,1030,700)')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,180','330,130')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,241','330,191')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,314+i*70','330,264+i*70')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,604','330,635')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','970,670','970,720')
edit('Presentation/BattleJobControls.cs','}else if(j.Id=="job.panzer"){','}else if(j.Id=="job.alchemist"){\n                DrawAlchemyBattleControls(actor,enabled,jobButton);\n            }else if(j.Id=="job.panzer"){')
print('Oriflamme connected.')
