"""Wire Shell into production while keeping historical capture catalogs stable."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=ROOT/'game/unity/Assets/Game/Scripts'
def edit(file,old,new):
    p=BASE/file;text=p.read_text(encoding='utf-8-sig')
    if new in text:return
    assert old in text,(file,old)
    p.write_text(text.replace(old,new),encoding='utf8')
edit('Core/PlayableBattle.cs','bool useJobRulesV2=false,int protectedSlot=0)','bool useJobRulesV2=false,int protectedSlot=0,PanzerLoadout panzerLoadout=null)')
edit('Core/PlayableBattle.cs','InitializeJobRules(useJobRulesV2,protectedSlot);','InitializeJobRules(useJobRulesV2,protectedSlot,panzerLoadout);')
for file in ['Core/PlayableBattle.cs','Core/HeroineSkillRules.cs']:
    edit(file,'selfDamageMaxHpPercent=s.selfDamageMaxHpPercent,','selfDamageMaxHpPercent=s.selfDamageMaxHpPercent,targetStatusBonusKind=s.targetStatusBonusKind,targetStatusBonusPercent=s.targetStatusBonusPercent,')
edit('Presentation/HeroineSanctuaryView.cs','skill.powerScale=id.StartsWith("heroine.annihilator",StringComparison.Ordinal)?','skill.powerScale=(id.StartsWith("heroine.annihilator",StringComparison.Ordinal) || id=="heroine.shell")?')
edit('Core/FormalCombatDefinitions.cs','resourceMax<1 || resourceMax>15','resourceMax<0 || resourceMax==0 && id!="job.panzer" || resourceMax>15')
edit('Core/PlayableBattle.cs','formationIds[i].StartsWith("heroine.annihilator",StringComparison.Ordinal))commandDefinitions','(formationIds[i].StartsWith("heroine.annihilator",StringComparison.Ordinal) || formationIds[i]=="heroine.shell"))commandDefinitions')
edit('Core/PlayableBattleJobRules.cs','InitializeJobRules(bool enabled,int protectedSlot)','InitializeJobRules(bool enabled,int protectedSlot,PanzerLoadout loadout)')
edit('Core/PlayableBattleJobRules.cs','if(Job(i,"panzer"))State.Heroes[i].InitializePanzer(()=>Clock);','if(Job(i,"panzer")){var l=loadout??new PanzerLoadout();var j=jobStates[i];j.ArmorResistance=l.Resistance;j.PanzerTools[0]=l.FirstTool;j.PanzerTools[1]=l.SecondTool;j.PanzerConfigured=true;State.Heroes[i].InitializePanzer(()=>Clock);State.Heroes[i].PanzerFireResistance=l.Resistance=="fire";int actor=i;State.Heroes[i].ArmorBroke=()=>RecordPresentation(BattlePresentationKind.Support,actor,"body","ARMOR BREAK ／ 生身で防御・300 Clock生存で再召喚",standalone:true);}')
edit('Core/HeroineSkillRules.cs','string resource=job.id=="job.healer"','string resource=job.id=="job.panzer"?"装甲中のみ使用可。装甲HPは通常回復不可、ツールで修復。生身は防御のみ":job.id=="job.healer"')
edit('Presentation/HeroineSanctuaryArt.cs','hero.StartsWith("heroine.annihilator",StringComparison.Ordinal)','(hero.StartsWith("heroine.annihilator",StringComparison.Ordinal) || hero=="heroine.shell")')
edit('Core/HeroineTraitRules.cs','job=="job.gunner" && stat=="physical-defense"','(job=="job.gunner" || job=="job.panzer") && stat=="physical-defense"')
edit('Data/HeroineIdentityCatalog.cs','id=="job.healer"?"ヒーラー":','id=="job.healer"?"ヒーラー":id=="job.panzer"?"パンツァー":')
edit('Data/HeroineIdentityCatalog.cs','default:throw new ArgumentException','case "heroine.shell":name="支えを選ぶ翼";master="帰ってくる装甲";icon="star";bonus="物理防御＋5%";break;\n                default:throw new ArgumentException')
edit('Data/HeroineIdentityCatalog.cs','string resource=job=="job.artist"','string resource=job=="job.panzer"?"装甲HPは通常回復不可。ツール2枠・各2回。生身は防御のみ、300 Clock生存で装甲復帰。":job=="job.artist"')
edit('Data/ProductionEconomyCatalog.cs','"贈り物の翼"};','"贈り物の翼","守護の拳","耐える装甲","帰還の回転翼"};')
edit('Data/ProductionEconomyCatalog.cs','6,8,12};','6,8,12,9,7,14};')
edit('Data/ProductionEconomyCatalog.cs','1.12f,1.2f,1.32f};','1.12f,1.2f,1.32f,1.2f,1.14f,1.36f};')
edit('Data/ProductionEconomyCatalog.cs','"紅蝶","雪灯"};','"紅蝶","雪灯","鋼翼"};')
edit('Data/ProductionEconomyCatalog.cs','hero<6?hero+1:hero==6?1:2','hero<6?hero+1:hero==6?1:hero==7?2:6')
edit('Data/ProductionEconomyCatalog.cs','heroIndex<6?heroIndex+1:heroIndex==6?1:2','heroIndex<6?heroIndex+1:heroIndex==6?1:heroIndex==7?2:6')
edit('Data/ProductionStoryCatalog.cs','Plan10AnnihilatorHomeArt.Apply(home);','Plan10AnnihilatorHomeArt.Apply(home);\n            Plan10ShellHomeArt.Apply(home);')
art=(BASE/'Data/Plan10AnnihilatorHomeArt.cs').read_text(encoding='utf8').replace('Plan10AnnihilatorHomeArt','Plan10ShellHomeArt').replace('new[]{"annihilator","annihilator-holy"}','new[]{"shell"}')
(BASE/'Data/Plan10ShellHomeArt.cs').write_text(art,encoding='utf8')
edit('Presentation/PrototypeBootstrap.cs','Environment.GetCommandLineArgs().Contains("-captureAnnihilator")?"Combat/battle-plan10-annihilator"','Environment.GetCommandLineArgs().Contains("-captureShell")?"Combat/battle-plan10-shell":Environment.GetCommandLineArgs().Contains("-captureAnnihilator")?"Combat/battle-plan10-annihilator"')
edit('Presentation/PrototypeBootstrap.cs','?"Combat/battle-formal":"Combat/battle-plan10-annihilator"','?"Combat/battle-formal":"Combat/battle-plan10-shell"')
edit('Presentation/PrototypeBootstrap.cs','PreparePlan10AnnihilatorCapture(args);','PreparePlan10AnnihilatorCapture(args);\n            PreparePlan10ShellCapture(args);')
edit('Presentation/PrototypeBootstrap.cs','protectedSlot:protectedFormationSlot);','protectedSlot:protectedFormationSlot,panzerLoadout:SavedPanzerLoadout());')
edit('Core/FormalHomeJournal.cs','"weapon","weapon-level","formation"','"weapon","weapon-level","panzer-loadout","formation"')
edit('Presentation/ProductionStoryExperience.cs','(Environment.GetCommandLineArgs().Contains("-captureAnnihilator")','(Environment.GetCommandLineArgs().Contains("-captureShell") || Environment.GetCommandLineArgs().Contains("-captureAnnihilator")')
edit('Presentation/ProductionStoryExperience.cs','combatDefinitions.HeroineIds.Contains("heroine.annihilator")?"Story/plan10-annihilator-story-content"','combatDefinitions.HeroineIds.Contains("heroine.shell")?"Story/plan10-shell-story-content":combatDefinitions.HeroineIds.Contains("heroine.annihilator")?"Story/plan10-annihilator-story-content"')
edit('Presentation/BattleIllustrationView.cs','new[]{"annihilator","annihilator-holy"}','new[]{"annihilator","annihilator-holy","shell"}')
edit('Presentation/AdvExperience.cs','actor.HeroineId=="heroine.r" ||','actor.HeroineId=="heroine.shell" || actor.HeroineId=="heroine.r" ||')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','new[]{"heroine.r","heroine.annihilator","heroine.annihilator-holy"}','new[]{"heroine.r","heroine.annihilator","heroine.annihilator-holy","heroine.shell"}')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','GrowthFrame(285,195,1030,505)','GrowthFrame(285,150,1030,590)')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,224','330,180')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,285','330,241')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,358+i*70','330,314+i*70')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','330,574','330,604')
edit('Presentation/Plan10AnnihilatorRecruitment.cs','970,628','970,670')
edit('Presentation/BattleMenuExperience.cs','"パス",enabled && !(encounter.JobState(actor)?.Singing??false)','encounter.RequiresPanzerDefense(actor)?"防御・装甲を待つ":"パス",enabled && (encounter.RequiresPanzerDefense(actor) || encounter.CanPass(actor))')
edit('Presentation/BattleMenuExperience.cs','ResetBattleMenu();encounter.Pass();QueueBattleEvents();','ResetBattleMenu();if(encounter.RequiresPanzerDefense(actor))encounter.DefendPanzer(actor);else encounter.Pass();QueueBattleEvents();')
edit('Presentation/BattleMenuExperience.cs','encounter.ResourceName(actor)+" "+(visual?.Resources[actor]??hero.JobResource)+"/"+hero.JobResourceMax','BattleResourceLine(actor,hero,visual)')
print('Production links and historical fixtures integrated.')
