using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
internal static class Plan10NighthawkTests
{
    public static void Run(Action<bool,string> check,string resources)
    {
        var options=new JsonSerializerOptions{IncludeFields=true};
        Func<CombatDefinitionCatalog> read=()=>JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-nighthawk.json")),options);
        var c=read();c.Validate();var old=JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-oriflamme.json")),options);
        check(c.HeroineIds.Length==11 && c.HeroineIds.Select(c.PersonId).Distinct().Count()==10 && c.jobs.Length==10,"Nighthawk eleventh form tenth person tenth job");
        foreach(var h in old.heroines){check(JsonSerializer.Serialize(h,options)==JsonSerializer.Serialize(c.Hero(h.id),options),"Prior heroine unchanged "+h.id);foreach(var id in h.skills)check(JsonSerializer.Serialize(old.skills.Single(s=>s.id==id),options)==JsonSerializer.Serialize(c.skills.Single(s=>s.id==id),options),"Prior skill unchanged "+id);}
        var growth=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=4321,stones=1234,heroines=c.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=20}).ToArray()};
        Func<int,PlayableBattle> fixture=slot=>{var defs=read();foreach(var j in defs.jobs)j.hp=100000;var ids=defs.FormationIds;ids[slot]="heroine.nighthawk";var enemy=ColossusCombatCatalog.Get(WorldCatalog.ColossusIds[0]);enemy.baseHp=10000000;enemy.hpPerLevel=1;var result=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:defs.WithFormation(ids),formalGrowth:growth,colossusDefinition:enemy,useJobRulesV2:true);result.State.BreakPart(result.State.Parts.Single(p=>p.Role=="drain").Id,int.MaxValue);return result;};
        Action<PlayableBattle,int> ready=(b,a)=>{int limit=0;while(b.AvailableHero!=a && !b.Ended && limit++<500)b.Pass();check(b.AvailableHero==a,"Chaser actor becomes READY");};
        foreach(int slot in Enumerable.Range(0,5)){var b=fixture(slot);ready(b,slot);check(b.JobState(slot).Id=="job.chaser" && b.SelectChaserGear(slot,2),"Chaser follows identity in every slot");}
        var battle=fixture(0);ready(battle,0);var hero=battle.State.Heroes[0];long clock=battle.Clock;int res=hero.JobResource;long regular=battle.RecoveryDelay(0,1);
        check(!battle.SelectChaserGear(1,2) && !battle.SelectChaserGear(0,0) && !battle.SelectChaserNitro(0),"Wrong actor invalid gear and empty nitro reject");
        check(battle.SelectChaserGear(0,3) && battle.RecoveryDelay(0,1)==Math.Max(1,regular*35/100) && battle.Clock==clock && hero.JobResource==res,"Gear preview changes wait without advancing or spending");
        check(!battle.Act(0,1,"missing") && hero.JobResource==res && battle.JobState(0).Gear==3 && battle.JobState(0).NitroCount==0,"Invalid attack preserves gear resource and nitro");
        check(battle.Act(0,1,"body") && battle.JobState(0).Gear==1 && battle.JobState(0).NitroCount==1 && battle.JobState(0).ChaserRecoveryPercent==35,"Paid gear commits once retains wait snapshot and resets selection");
        check(battle.NextAt(0)==clock+Math.Max(1,regular*35/100),"Committed GEAR3 wait matches preview after automatic reset");
        ready(battle,0);
        for(int n=1;n<5;n++){hero.GainResource(15);check(battle.SelectChaserGear(0,2) && battle.Act(0,0,"body"),"Paid buff contributes one nitro");ready(battle,0);}
        check(battle.JobState(0).NitroCount==5,"Five paid commands fill five nitro");clock=battle.Clock;res=hero.JobResource;
        check(battle.SelectChaserNitro(0) && battle.JobState(0).NitroCount==5 && battle.RecoveryDelay(0,0)==0,"NITRO reserves without spending");
        check(!battle.Act(0,1,"missing") && battle.JobState(0).NitroSelected && battle.JobState(0).NitroCount==5,"Invalid nitro command preserves reservation");
        check(battle.Act(0,0,"body") && battle.Clock==clock && battle.AvailableHero==0 && battle.JobState(0).NitroCount==0 && hero.JobResource==res,"NITRO buff consumes five returns READY at identical clock and costs no gear");
        check(!battle.SelectChaserNitro(0) && battle.RecoveryDelay(0,0)>0,"Spent NITRO cannot repeat zero wait");
        var nitroAttack=fixture(0);ready(nitroAttack,0);nitroAttack.JobState(0).NitroCount=5;clock=nitroAttack.Clock;check(nitroAttack.SelectChaserNitro(0) && nitroAttack.Act(0,1,"body") && nitroAttack.Clock==clock && nitroAttack.AvailableHero==0 && nitroAttack.JobState(0).NitroCount==0,"NITRO attack also returns immediately to READY");
        var insufficient=fixture(0);ready(insufficient,0);check(insufficient.SelectChaserGear(0,3),"Select affordable gear before resource changes");insufficient.State.Heroes[0].SpendResource(insufficient.State.Heroes[0].JobResource);check(!insufficient.Act(0,0,"body") && insufficient.JobState(0).NitroCount==0 && insufficient.State.Heroes[0].TimedSpeedPercent==0,"Resource loss after selection rejects atomically");
        var capped=fixture(0);ready(capped,0);capped.JobState(0).NitroCount=10;check(capped.SelectChaserGear(0,2) && capped.Act(0,0,"body") && capped.JobState(0).NitroCount==10,"NITRO cap prevents overflow");
        var skip=fixture(0);ready(skip,0);skip.JobState(0).NitroCount=5;check(skip.SelectChaserNitro(0),"Reserve nitro before status changes");skip.State.Heroes[0].AddStatus(new EnemyStatusDef{kind="stun",amount=1000});check(!skip.Act(0,0,"body") && skip.JobState(0).NitroCount==5,"Stun rejects nitro consumption");skip.State.Heroes[0].Status.ClearAll();skip.Pass();skip.State.Heroes[0].AddStatus(new EnemyStatusDef{kind="stun",amount=1000});long skipStart=skip.Clock;ready(skip,0);check(skip.Clock>skipStart && skip.JobState(0).NitroCount==5 && skip.JobState(0).NitroSelected,"Forced status skip advances time and preserves reserved nitro");
        var ticks=fixture(0);ready(ticks,0);long started=ticks.Clock;int initial=ticks.State.Heroes[0].JobResource;while(ticks.Clock<started+300 && !ticks.Ended)ticks.Pass();check(ticks.State.Heroes[0].JobResource==Math.Min(15,initial+2*(int)(ticks.Clock/100-started/100)),"Gear restores two at each crossed clock boundary");
        var flags=new EnemyStatusState();check(!flags.AddIgnition() && !flags.AddIgnition() && flags.IgnitionFlags==2,"Two ignition flags accumulate");flags.Tick();check(flags.IgnitionFlags==2 && flags.AddIgnition() && flags.IgnitionFlags==0,"Third flag resets independently of timed status");flags.AddIgnition();flags.ClearAll();check(flags.IgnitionFlags==0,"Clearing target status clears ignition");
        var ignition=fixture(0);ready(ignition,0);ignition.DrainPresentationEvents();ignition.State.BossStatus.AddIgnition();ignition.State.BossStatus.AddIgnition();check(ignition.Act(0,1,"body"),"Ignition source attack executes");var events=ignition.DrainPresentationEvents();check(events.Count(e=>e.Message.Contains("OVER IGNITION"))==1 && ignition.State.BossStatus.IgnitionFlags==0,"Third source hit triggers one nonrecursive reaction");check(ignition.State.Parts.Where(p=>!p.IsBroken).All(p=>p.Status.IgnitionFlags==0),"Reaction does not spread ignition flags to other targets");
        var frozen=fixture(0);ready(frozen,0);int plain=frozen.PreviewDamage(0,1,"body"),part=frozen.PreviewDamage(0,1,frozen.State.Parts[0].Id);frozen.State.BossStatus.Add(new EnemyStatusDef{kind="frostbite",amount=1000});check(frozen.PreviewDamage(0,1,"body")>plain*1.5 && frozen.PreviewDamage(0,1,frozen.State.Parts[0].Id)==part,"Frost bonus is target local");
        var buff=fixture(0);ready(buff,0);check(buff.Act(0,0,"body") && buff.State.Heroes[0].TimedSpeedPercent==20 && buff.State.Heroes[0].TimedEffects.Any(e=>e.Kind=="attack"),"Both source self effects apply");for(int i=0;i<6;i++)buff.State.Heroes[0].TickBattleTurn();check(buff.State.Heroes[0].TimedSpeedPercent==0,"Speed expires after six battle turns");
        var ultimate=fixture(0);ready(ultimate,0);check(ultimate.Act(0,2,"body") && ultimate.State.BossStatus.Meter("burn")>0 && ultimate.State.BossStatus.Meter("frostbite")>0,"Ultimate applies both target statuses");check(c.skills.Single(s=>s.id=="heroine.nighthawk.3").chainChanceBonusBp==1500,"Ultimate authored connection bonus is fifteen percent");
        var multi=fixture(0);ready(multi,0);multi.State.BossStatus.AddIgnition();multi.State.BossStatus.AddIgnition();foreach(var target in multi.State.Parts.Where(p=>!p.IsBroken)){target.Status.AddIgnition();target.Status.AddIgnition();}multi.DrainPresentationEvents();check(multi.Act(0,2,"body") && multi.DrainPresentationEvents().Count(e=>e.Message.Contains("OVER IGNITION"))==1,"Several third flags in one AOE cause only one reaction");
        bool chainReaction=false;for(int n=0;n<20 && !chainReaction;n++){var chained=fixture(1);ready(chained,0);chained.State.BossStatus.AddIgnition();chained.State.BossStatus.AddIgnition();chained.DrainPresentationEvents();chained.Act(0,n%2,"body");chainReaction=chained.DrainPresentationEvents().Any(e=>e.Actor==1 && e.Message.Contains("OVER IGNITION"));}check(chainReaction,"Nighthawk fixed chain contributes to ignition");
        var invalid=read();invalid.skills.Last().chainChanceBonusBp=1501;bool rejected=false;try{invalid.Validate();}catch(ArgumentException){rejected=true;}check(rejected,"Out of range authored chain bonus rejects");
        Console.WriteLine("PLAN10_NIGHTHAWK_COMBAT_PASS gears / nitro / ignition / source skills / five positions");
        if(Environment.GetEnvironmentVariable("NEWASTER_PLAN10_NIGHTHAWK_ART")!="1")return;
        var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-nighthawk-story-content.json")),options);story.Validate(c.HeroineIds,WorldCatalog.ColossusIds.ToArray());var home=ProductionStoryCatalog.Home(c,story);home.Validate(true);
        check(home.weaponNodes.Count(n=>n.heroineId=="heroine.nighthawk")==13 && home.assets.All(a=>!a.placeholder),"Thirteen weapon nodes dedicated adopted art");check(story.chapters.Where(x=>x.ownerId=="heroine.nighthawk").Sum(x=>x.pages.Length)==30 && story.events.Count(e=>e.ownerId=="heroine.nighthawk")==5,"Thirty pages five relationship events");
        var reordered=read();Array.Reverse(reordered.heroines);var reorderHome=ProductionStoryCatalog.Home(reordered,story);check(home.weaponNodes.Select(n=>n.id+"="+n.weaponTraitName).OrderBy(n=>n).SequenceEqual(reorderHome.weaponNodes.Select(n=>n.id+"="+n.weaponTraitName).OrderBy(n=>n)),"Weapon owners remain stable when heroine ordering changes");
        var prior=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=4321,stones=1234,heroines=old.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=20}).ToArray()};var p=new FormalProgression(prior,c.HeroineIds);var request=new GrowthRequest("nighthawk-free","heroine.nighthawk",prior.revision,GrowthOperation.ReceiveHeroine);check(p.Commit(request,s=>false)==GrowthCommitResult.SaveFailed && p.Snapshot.heroines.Length==10,"Recruit failure preserves prior ten forms");check(p.Commit(request,s=>true)==GrowthCommitResult.Committed && p.Commit(request,s=>false)==GrowthCommitResult.AlreadyCommitted && p.Snapshot.nectar==4321 && p.Snapshot.stones==1234,"Free recruit persists once and preserves currency");
        var restored=JsonSerializer.Deserialize<FormalGrowthSave>(JsonSerializer.Serialize(p.Snapshot,options),options);restored.Validate();check(restored.heroines.Length==11 && restored.heroines.Single(h=>h.heroineId=="heroine.nighthawk").level==1,"Stable heroine identity round trips");
        Console.WriteLine("PLAN10_NIGHTHAWK_CONTENT_PASS compatible saves / growth / narrative / art");
    }
}
