using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
public static class Plan13AffectionTests
{
    public static void Run(Action<bool,string> check,string resources)
    {
        var options=new JsonSerializerOptions{IncludeFields=true};Func<FormalCampaignSave,string> encode=s=>JsonSerializer.Serialize(s,options);Func<string,FormalCampaignSave> decode=t=>JsonSerializer.Deserialize<FormalCampaignSave>(t,options);
        var combat=JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-shangrila.json")),options);
        var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-shangrila-story-content.json")),options);var home=ProductionStoryCatalog.Home(combat,story);
        Func<FormalCampaignSave> fresh=()=>{var s=new FormalCampaignSave{world=new CampaignState(WorldCatalog.ColossusIds).CreateSave(),growth=new FormalGrowthSave{saveId="newaster.formal-growth",stones=30000,heroines=combat.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id}).ToArray()},home=FormalHomeProgress.Empty(home.contentVersion),collection=new FormalCollectionLedger{contentVersion=CollectionCatalog.ProductionVersion}};AffectionSaveAdapter.Migrate(s,home);return s;};
        Action<Action,string> reject=(f,label)=>{bool bad=false;try{f();}catch(Exception e)when(e is ArgumentException || e is InvalidOperationException){bad=true;}check(bad,label);};
        var save=fresh();string form="heroine.slayer";var a=AffectionService.State(save,home,form);a.exp=95;AffectionService.Add(a,108,save.affection);check(a.level==2 && a.exp==3,"AF-01 EXP100 levels up and carries excess");
        a.level=9;a.exp=99;AffectionService.Add(a,1,save.affection);check(a.level==10 && a.exp==0 && AffectionService.IsLover(a),"AF-02 Lv10 automatically establishes lover without reading an event");
        a.level=19;a.exp=99;AffectionService.Add(a,500,save.affection);check(a.level==20 && a.exp==0,"AF-03 normal cap discards excess EXP");AffectionService.Add(a,5,save.affection);check(a.exp==0,"AF-03 capped EXP remains zero");
        AffectionRingService.Purchase(save);int stones=save.growth.stones;AffectionRingService.Use(save,home,form);check(a.levelCap==99 && save.growth.eternalRings==0 && stones==20000,"AF-04 one shared inventory ring opens cap99 immediately");reject(()=>AffectionRingService.Use(save,home,form),"AF-04 ring cannot be reused or reassigned");
        a.level=98;a.exp=99;AffectionService.Add(a,800,save.affection);check(a.level==99 && a.exp==0,"AF-03 extended cap discards excess EXP");
        var journal=new FormalCampaignJournal(fresh(),encode,decode);FormalCampaignSave disk=null;var buy=new AffectionRequest("af.purchase",journal.Revision,"ring-purchase",Array.Empty<string>(),"ring");string before=encode(journal.Snapshot);
        check(journal.CommitAffection(buy,home,s=>false)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"AF-05 purchase failure consumes no stones or rings");
        check(journal.CommitAffection(buy,home,s=>{s.growth.stones=0;return false;})==GrowthCommitResult.SaveFailed,"AF-11 failed writer cannot change frozen candidate");
        check(journal.CommitAffection(buy,home,s=>{disk=decode(encode(s));return true;})==GrowthCommitResult.Committed && journal.Snapshot.growth.stones==20000 && journal.Snapshot.growth.eternalRings==1,"AF-05 purchase retry commits exact cost once");
        var restarted=new FormalCampaignJournal(disk,encode,decode);check(restarted.CommitAffection(buy,home,s=>throw new Exception("duplicate writer"))==GrowthCommitResult.AlreadyCommitted,"AF-05 purchase replay after restart does not consume twice");
        var useSave=journal.Snapshot;AffectionService.State(useSave,home,form).level=20;journal=new FormalCampaignJournal(useSave,encode,decode);var use=new AffectionRequest("af.use",journal.Revision,"ring-use",new[]{form},"ring");before=encode(journal.Snapshot);
        check(journal.CommitAffection(use,home,s=>false)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"AF-05 use failure preserves ring and cap");check(journal.CommitAffection(use,home,s=>true)==GrowthCommitResult.Committed && AffectionService.State(journal.Snapshot,home,form).levelCap==99 && journal.Snapshot.growth.eternalRings==0,"AF-05 use retry changes cap and spends one ring atomically");check(journal.CommitAffection(use,home,s=>throw new Exception())==GrowthCommitResult.AlreadyCommitted,"AF-05 duplicate use does not spend again");
        var shared=fresh();check(ReferenceEquals(AffectionService.State(shared,home,form),AffectionService.State(shared,home,"heroine.slayer-swim")),"AF-06 outfits refer to one person state");
        a=AffectionService.State(shared,home,form);a.level=20;AffectionEventResolver.Refresh(shared,home);check(home.events.Where(e=>e.heroineId==form).All(e=>shared.home.unlockedEventIds.Contains(e.id)) && shared.home.readEventIds.Length==0,"AF-07 all Lv-qualified events unlock without preceding reads");
        var ev=home.events.First(e=>e.heroineId==form);var replay=new AdvSession(home,ev.sceneId,ev.id,true,Array.Empty<HomeReadLine>());while(!replay.EndReached){replay.Tick(2);replay.Advance();}before=encode(shared);var replayJournal=new FormalCampaignJournal(shared,encode,decode);
        reject(()=>replayJournal.CommitAdvEnd(new FormalHomeRequest("af.replay","sceneEnd",shared.revision,home.contentVersion,ev.id+"/"+ev.sceneId+"/1"),home,replay,s=>true),"AF-08 replay cannot commit progress or rewards");check(replay.NewlyRead.Count==0 && before==encode(replayJournal.Snapshot),"AF-08 replay preserves EXP wallet read flags and campaign");
        var repeated=fresh();int[] gains={5,3,1,1};for(int i=0;i<4;i++)check(AffectionRewardService.Interaction(repeated,home,form,"conversation.a")==gains[i],"AF-10 same content diminishing award "+i);check(AffectionRewardService.Interaction(repeated,home,"heroine.slayer-swim","conversation.b")==5 && AffectionRewardService.Interaction(repeated,home,form,"conversation.a")==5,"AF-10 different conversation resets the shared-person streak");
        check(AffectionRewardService.Interaction(repeated,home,form,"together/bench.1/sit")==5 && AffectionRewardService.Interaction(repeated,home,form,"together/bench.1/sit")==3 && AffectionRewardService.Interaction(repeated,home,form,"together/bench.1/read")==5,"AF-10 furniture identity and interaction define content");
        var session=new AffectionInteractionSession("af.session",form,"conversation.a",GardenLifeCatalog.GardenIds[0],4);session.Tick(2,false);check(!session.Completed,"AF-10 inactive waiting does not complete player interaction");session.Tick(2,true);session.Cancel();session.Tick(2,true);check(session.Cancelled && !session.Completed,"AF-10 cancelled interaction never completes or grants EXP");
        journal=new FormalCampaignJournal(fresh(),encode,decode);var reward=new AffectionRequest("af.reward",journal.Revision,"interaction",new[]{form},"conversation.a");before=encode(journal.Snapshot);check(journal.CommitAffection(reward,home,s=>false)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"AF-11 reward failure publishes neither EXP nor streak");check(journal.CommitAffection(reward,home,s=>{disk=s;return true;})==GrowthCommitResult.Committed && AffectionService.State(journal.Snapshot,home,form).exp==5,"AF-11 reward retry awards once");check(new FormalCampaignJournal(disk,encode,decode).CommitAffection(reward,home,s=>throw new Exception())==GrowthCommitResult.AlreadyCommitted,"AF-11 reward replay after restart is idempotent");
        var old=fresh();old.affection=null;old.home.affections=new[]{new HomeAffection{heroineId=form,value=7},new HomeAffection{heroineId="heroine.slayer-swim",value=14},new HomeAffection{heroineId="heroine.r",value=100}};old.home.readEventIds=new[]{form+".event.0"};old.home.unlockedEventIds=old.home.readEventIds;string oldHome=JsonSerializer.Serialize(old.home,options);AffectionSaveAdapter.Migrate(old,home);
        check(AffectionService.State(old,home,form).level==14 && AffectionService.State(old,home,form).readEventIds.SequenceEqual(new[]{form+".event.0"}) && JsonSerializer.Serialize(old.home,options)==oldHome,"AF-12 maximum legacy person value and all read flags remain intact");check(AffectionService.State(old,home,"heroine.r").level==99 && AffectionService.State(old,home,"heroine.r").levelCap==99 && old.affection.legacyValues.Any(v=>v.value==100),"AF-12 out-of-range legacy original preserved with safe cap99 migration");before=encode(old);AffectionSaveAdapter.Migrate(old,home);check(before==encode(old),"AF-12 migration is idempotent");
        var many=fresh();many.affection=null;many.home=FormalHomeProgress.Empty(home.contentVersion);many.growth.heroines=Enumerable.Range(0,256).Select(i=>new FormalHeroineGrowth{heroineId="heroine.test."+i}).ToArray();AffectionSaveAdapter.Migrate(many,home);foreach(var state in many.affection.states)AffectionService.Add(state,105,many.affection);many.affection.Validate();check(many.affection.states.Length==256 && many.affection.states.All(state=>state.level==1 && state.exp==5),"AF-13 256 independent person states advance without fixed array limits");
        var max=fresh();a=AffectionService.State(max,home,form);a.level=98;a.levelCap=99;a.exp=99;AffectionService.Add(a,1,max.affection);AffectionService.Add(a,8,max.affection);check(max.affection.pendingMaxLevelPersonIds.Length==1,"AF-14 reaching Lv99 queues exactly one display");journal=new FormalCampaignJournal(max,encode,decode);var shown=new AffectionRequest("af.max",journal.Revision,"max-display",new[]{form},"max-level");check(journal.CommitAffection(shown,home,s=>false)==GrowthCommitResult.SaveFailed && journal.Snapshot.affection.pendingMaxLevelPersonIds.Length==1,"AF-14 failed milestone save leaves the display pending");check(journal.CommitAffection(shown,home,s=>true)==GrowthCommitResult.Committed && journal.Snapshot.affection.pendingMaxLevelPersonIds.Length==0 && journal.Snapshot.affection.shownMaxLevelPersonIds.Length==1,"AF-14 milestone acknowledgement is durable");max=journal.Snapshot;AffectionService.Add(AffectionService.State(max,home,form),100,max.affection);check(max.affection.pendingMaxLevelPersonIds.Length==0,"AF-14 subsequent capped rewards never repeat the display");
        var battle=fresh();var collection=ProductionStoryCatalog.Collection(combat,story);var owner=collection.owners.First(o=>WorldCatalog.ColossusIds.Contains(o.id));journal=new FormalCampaignJournal(battle,encode,decode);
        foreach(var reason in new[]{BattleEndReason.Victory,BattleEndReason.Victory,BattleEndReason.Defeat,BattleEndReason.Retreat}){
            var snap=journal.Snapshot;var collected=new BattleCollectionSession(collection,"af.battle."+snap.revision,owner.id,1,snap.revision,combat.FormationIds).Finish(reason,snap.world.poemIds,snap.world.unlockedStoryIds);var req=new FormalBattleEndRequest(collected,snap.revision);
            Func<CampaignSaveV2,CampaignSaveV2> victory=w=>{var state=new CampaignState(WorldCatalog.ColossusIds,w);state.ClaimColossusVictory(owner.id,WorldCatalog.Colossi.First(c=>c.Id==owner.id).EnvironmentTags,new VictoryReward(req.Id,1,1,1,Array.Empty<string>()),Array.Empty<StoryRequirement>(),Array.Empty<TerraformingMilestone>(),GardenCatalog.Requirements);return state.CreateSave();};
            before=encode(snap);check(journal.CommitBattleEnd(req,collection,victory,s=>false,home)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"AF-09/11 battle EXP is part of the atomic battle candidate "+reason);check(journal.CommitBattleEnd(req,null,null,s=>true)==GrowthCommitResult.Committed,"AF-09 battle result retries without duplicate affection "+reason);
        }
        check(combat.FormationIds.All(id=>AffectionService.State(journal.Snapshot,home,id).exp==5),"AF-09 repeat victory+2 defeat+1 retreat0 for every deployed person");
        var longRun=fresh();var longState=AffectionService.State(longRun,home,form);for(int i=0;i<400;i++)AffectionRewardService.Interaction(longRun,home,form,"conversation."+(i%2));
        check(longState.level==20 && longState.exp==0 && longRun.growth.stones==30000,"AF-01/03 Lv0 to20 through completed interactions has no cap reward");AffectionRingService.Purchase(longRun);AffectionRingService.Use(longRun,home,form);for(int i=0;i<1580;i++)AffectionRewardService.Interaction(longRun,home,form,"conversation."+(i%2));
        check(longState.level==99 && longState.exp==0 && longRun.growth.stones==20000 && longRun.growth.eternalRings==0,"AF-01/04 complete Lv0->20->ring->99 progression with no additional rewards");
        check(decode(encode(longRun)).affection.states.Single(state=>state.personId==home.PersonId(form)).level==99,"AF-12 long-term Lv99 progress survives serialization");
        var discovered=fresh();discovered.world.unlockedGardenIds=GardenLifeCatalog.GardenIds;GardenLifeCatalog.Migrate(discovered);var runtime=new GardenLifeRuntime(discovered,home,GardenLifeCatalog.GardenIds[0]);var context=runtime.Context();context.timePhase="morning";context.participantIds=new[]{form,"heroine.slayer-swim"};
        var discovery=GardenLifeCatalog.Discoveries.First(d=>d.condition=="morning");var tx=new GardenDiscoveryTransaction("af.discovery",discovery.id,context);var lifeRequest=new GardenLifeRequest(tx.Id,"discovery",discovered.revision,"morning");journal=new FormalCampaignJournal(discovered,encode,decode);before=encode(journal.Snapshot);
        check(journal.CommitGardenLife(lifeRequest,home,tx.Apply,state=>false)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"AF-11 discovery and participant EXP both remain unpublished on failure");
        check(journal.CommitGardenLife(lifeRequest,home,state=>throw new Exception("rebuilt"),state=>true)==GrowthCommitResult.Committed && AffectionService.State(journal.Snapshot,home,form).exp==3,"AF-06/11 discovery retry awards3 once to each participating person across outfits");
        check(journal.CommitGardenLife(lifeRequest,home,null,state=>throw new Exception("duplicate"))==GrowthCommitResult.AlreadyCommitted,"AF-11 discovery replay grants no duplicate EXP");
        Console.WriteLine("PLAN13_AFFECTION_PASS AF-01..AF-14 / person migration / atomic rings / repeat battle / replay / 256 persons");
    }
}
