using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
internal static class Plan10OriflammeTests
{
    public static void Run(Action<bool,string> check,string resources)
    {
        var options=new JsonSerializerOptions{IncludeFields=true};
        Func<CombatDefinitionCatalog> read=()=>JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-oriflamme.json")),options);
        var c=read();c.Validate();var old=JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-shell.json")),options);
        check(c.HeroineIds.Length==10 && c.HeroineIds.Select(c.PersonId).Distinct().Count()==9 && c.jobs.Length==9,"Oriflamme tenth form ninth person ninth job");
        foreach(var h in old.heroines){check(JsonSerializer.Serialize(h,options)==JsonSerializer.Serialize(c.Hero(h.id),options),"Prior heroine unchanged "+h.id);foreach(var id in h.skills)check(JsonSerializer.Serialize(old.skills.Single(s=>s.id==id),options)==JsonSerializer.Serialize(c.skills.Single(s=>s.id==id),options),"Prior skill unchanged "+id);}
        var growth=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=4321,stones=1234,heroines=c.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=20}).ToArray()};
        Func<int,PlayableBattle> fixture=slot=>{var defs=read();foreach(var j in defs.jobs)j.hp=100000;var ids=defs.FormationIds;ids[slot]="heroine.oriflamme";var enemy=ColossusCombatCatalog.Get(WorldCatalog.ColossusIds[0]);enemy.baseHp=10000000;enemy.hpPerLevel=1;var result=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:defs.WithFormation(ids),formalGrowth:growth,colossusDefinition:enemy,useJobRulesV2:true);result.State.BreakPart(result.State.Parts.Single(p=>p.Role=="drain").Id,int.MaxValue);return result;};
        Action<PlayableBattle,int> ready=(b,a)=>{int limit=0;while(b.AvailableHero!=a && !b.Ended && limit++<500)b.Pass();check(b.AvailableHero==a,"Alchemy actor becomes READY");};
        foreach(int slot in Enumerable.Range(0,5)){var b=fixture(slot);ready(b,slot);check(b.JobState(slot).Id=="job.alchemist" && b.AlchemyAttributes(slot).Length==5 && b.AlchemyAttributes(slot).Distinct().Count()==5,"Five-attribute job follows identity in every slot");}
        var battle=fixture(0);ready(battle,0);var hero=battle.State.Heroes[0];long clock=battle.Clock;int res=hero.JobResource,chain=battle.Chain;
        foreach(var invalid in new[]{new[]{0,0,0,0,0},new[]{-1,1,0,0,0},new[]{16,0,0,0,0},new[]{6,0,0,0,0},new[]{1,2}})check(!battle.Transmute(0,invalid,"body") && hero.JobResource==res && battle.Clock==clock,"Invalid inputs reject atomically");
        check(!battle.Transmute(1,new[]{1,0,0,0,0},"body") && !battle.Transmute(0,new[]{1,0,0,0,0},"missing") && !battle.Transmute(0,new[]{1,0,0,0,0},"body",true),"Wrong owner target and incomplete weakness reject");
        int hp=battle.State.BossHitPoints;check(battle.Transmute(0,new[]{2,2,1,0,0},"body") && battle.State.BossHitPoints<hp,"Mixed attribute recipe deals magic damage");check(hero.JobResource==res-5 && battle.Clock==clock && battle.AvailableHero==0 && battle.Chain==chain && !battle.Acted[0],"Alchemy consumes once and preserves READY Clock chain acted flag");
        check(!battle.Transmute(0,new[]{1,0,0,0,0},"body") && hero.JobResource==0,"Zero resource cannot loop freely");check(battle.Act(0,0,"body"),"Standard skill works with zero alchemy resource");ready(battle,0);check(hero.JobResource==3,"Source skill plus two and normal command plus one actual="+hero.JobResource);check(battle.State.BossStatus.FireVulnerabilityPercent==20 && battle.State.BossStatus.FireVulnerabilityTurns>0,"Incinerate installs target-local invasion");
        var weak=fixture(0);ready(weak,0);int before=weak.PreviewDamage(0,0,"body"),part=weak.PreviewDamage(0,0,weak.State.Parts[0].Id);check(weak.Transmute(0,new[]{2,0,0,1,0},"body",true) && weak.PreviewDamage(0,0,"body")>before && weak.PreviewDamage(0,0,weak.State.Parts[0].Id)==part,"Weakness enhances selected target only");var status=weak.State.BossStatus;status.Tick();status.Tick();check(status.FireVulnerabilityTurns==1,"Weakness lasts three ticks");status.Tick();check(status.FireVulnerabilityPercent==0 && weak.PreviewDamage(0,0,"body")==before,"Weakness expires exactly");
        var buff=fixture(0);ready(buff,0);int resource=buff.State.Heroes[0].JobResource;check(buff.Act(0,1,"body"),"Purifying fire executes");check(buff.State.Heroes.Where(h=>h.IsAlive).All(h=>h.FireAmplificationPercent>0 && h.TimedEffects.Any(e=>e.Kind=="attack")) && buff.State.Heroes[0].JobResource==resource+4,"Buff applies both effects to all living allies and restores alchemist resource");
        var ultimate=fixture(0);ready(ultimate,0);int plain=ultimate.PreviewDamage(0,2,"body"),separate=ultimate.PreviewDamage(0,2,ultimate.State.Parts[0].Id);ultimate.State.BossStatus.Add(new EnemyStatusDef{kind="burn",amount=1000});check(ultimate.PreviewDamage(0,2,"body")>plain*2 && ultimate.PreviewDamage(0,2,ultimate.State.Parts[0].Id)==separate,"Ultimate plus120 burning bonus never leaks across targets");check(ultimate.Act(0,2,"body") && ultimate.State.BossStatus.FireVulnerabilityPercent==30,"Ultimate installs authored fire resonance");
        var attributes=AlchemyRules.Attributes("heroine.oriflamme");attributes[0]="water";var recipe=AlchemyRules.Recipes("heroine.oriflamme")[0];var inputs=recipe.Units;inputs[0]=99;check(AlchemyRules.Attributes("heroine.oriflamme")[0]=="火" && recipe.Units[0]==3,"Attribute and recipe data are immutable copies");
        var damageBattle=fixture(0);var h0=damageBattle.State.Heroes[0];var fire=new BattleSkill("test",1,0,damageType:"magic",attributes:new[]{"火"});var water=new BattleSkill("test",1,0,damageType:"magic",attributes:new[]{"水"});int fireBefore=BattleActionResolver.CalculateDamage(damageBattle.State,h0,fire,"body"),waterBefore=BattleActionResolver.CalculateDamage(damageBattle.State,h0,water,"body");h0.ApplySelfEffects(new[]{new TimedSelfEffectDef{kind="fire-amplification",percent=30,turns=3}});check(BattleActionResolver.CalculateDamage(damageBattle.State,h0,fire,"body")>fireBefore && BattleActionResolver.CalculateDamage(damageBattle.State,h0,water,"body")==waterBefore,"Fire amplification leaves other attributes unchanged");
        var fixedDefs=c.WithFormation(new[]{"heroine.oriflamme"}.Concat(c.FormationIds.Skip(1)).ToArray());var fixedAction=fixedDefs.Chain()[0];check(fixedAction.Attributes.SequenceEqual(new[]{"火"}),"Oriflamme fixed chain carries her fire attribute");var fixedBattle=fixture(0);int fixedBefore=ChainActionResolver.Resolve(fixedBattle.State,0,fixedAction).Amount;fixedBattle.State.BossStatus.SetFireVulnerability(30,3);check(ChainActionResolver.Resolve(fixedBattle.State,0,fixedAction).Amount>fixedBefore && fixedBattle.State.Heroes[0].JobResource==5,"Fire vulnerability reaches fixed chain without consuming resources");
        var invalidDefs=read();invalidDefs.skills.Last().enemyFireVulnerabilityTurns=0;bool rejected=false;try{invalidDefs.Validate();}catch(ArgumentException){rejected=true;}check(rejected,"Malformed duration contract rejects before encounter");
        var denied=fixture(0);ready(denied,0);int deniedResource=denied.State.Heroes[0].JobResource;denied.State.Heroes[0].AddStatus(new EnemyStatusDef{kind="stun",amount=1000});check(!denied.Transmute(0,new[]{1,0,0,0,0},"body") && denied.State.Heroes[0].JobResource==deniedResource,"Stunned actor cannot transmute or spend");
        var brokenTarget=fixture(0);ready(brokenTarget,0);string target=brokenTarget.State.Parts[0].Id;brokenTarget.State.BreakPart(target,int.MaxValue);check(!brokenTarget.Transmute(0,new[]{1,0,0,0,0},target),"Broken part cannot receive alchemy");
        status.SetFireVulnerability(20,3);status.SetFireVulnerability(30,4);check(status.FireVulnerabilityPercent==30 && status.FireVulnerabilityTurns==4,"Reapplication replaces vulnerability without unbounded stacking");status.ClearAll();check(status.FireVulnerabilityPercent==0 && status.FireVulnerabilityTurns==0,"Cleared target loses vulnerability");
        var exhausted=fixture(0);ready(exhausted,0);exhausted.Transmute(0,new[]{5,0,0,0,0},"body");exhausted.Pass();ready(exhausted,0);check(exhausted.State.Heroes[0].JobResource==0,"PASS gives no alchemy resources");check(fixture(0).State.Heroes[0].JobResource==5,"New encounter resets alchemy resource");
        Console.WriteLine("PLAN10_ORIFLAMME_COMBAT_PASS recipes / atomic resources / target-local fire / five positions");
        if(Environment.GetEnvironmentVariable("NEWASTER_PLAN10_ORIFLAMME_ART")!="1")return;
        var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-oriflamme-story-content.json")),options);story.Validate(c.HeroineIds,WorldCatalog.ColossusIds.ToArray());var home=ProductionStoryCatalog.Home(c,story);home.Validate(true);
        check(home.weaponNodes.Count(n=>n.heroineId=="heroine.oriflamme")==13 && home.assets.All(a=>!a.placeholder),"Thirteen weapon nodes dedicated adopted art");check(story.chapters.Where(x=>x.ownerId=="heroine.oriflamme").Sum(x=>x.pages.Length)==30 && story.events.Count(e=>e.ownerId=="heroine.oriflamme")==5,"Thirty pages five relationship events");
        var prior=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=4321,stones=1234,heroines=old.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=20}).ToArray()};var p=new FormalProgression(prior,c.HeroineIds);var request=new GrowthRequest("oriflamme-free","heroine.oriflamme",prior.revision,GrowthOperation.ReceiveHeroine);check(p.Commit(request,s=>false)==GrowthCommitResult.SaveFailed && p.Snapshot.heroines.Length==9,"Recruit failure preserves prior nine forms");check(p.Commit(request,s=>true)==GrowthCommitResult.Committed && p.Commit(request,s=>false)==GrowthCommitResult.AlreadyCommitted && p.Snapshot.nectar==4321 && p.Snapshot.stones==1234,"Free recruit persists once and preserves currency");
        var restored=JsonSerializer.Deserialize<FormalGrowthSave>(JsonSerializer.Serialize(p.Snapshot,options),options);restored.Validate();check(restored.heroines.Length==10 && restored.heroines.Single(h=>h.heroineId=="heroine.oriflamme").level==1,"Stable heroine identity round-trips");
        var collection=ProductionStoryCatalog.Collection(c,story);var save=new FormalCampaignSave{growth=restored,world=new CampaignState(WorldCatalog.ColossusIds).CreateSave(),home=FormalHomeProgress.Empty(home.contentVersion),collection=new FormalCollectionLedger{contentVersion=collection.contentVersion}};HomeConditions.Refresh(save,home);save.Validate();save.home.ValidateContent(home,save);
        var equipped=JsonSerializer.Deserialize<FormalCampaignSave>(JsonSerializer.Serialize(save,options),options);equipped.home.weaponNodeIds=equipped.home.weaponNodeIds.Union(new[]{"heroine.oriflamme.weapon.alpha"}).ToArray();equipped.home.weaponEquipment=new[]{new HomeWeaponEquipment{heroineId="heroine.oriflamme",nodeId="heroine.oriflamme.weapon.alpha"}};var equipIds=new[]{"heroine.oriflamme"}.Concat(c.FormationIds.Skip(1)).ToArray();var plainWeapon=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:c.WithFormation(equipIds),formalGrowth:restored,homeProgress:save.home,homeCatalog:home,useJobRulesV2:true);var armed=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:c.WithFormation(equipIds),formalGrowth:restored,homeProgress:equipped.home,homeCatalog:home,useJobRulesV2:true);ready(plainWeapon,0);ready(armed,0);check(armed.PreviewDamage(0,0,"body")>plainWeapon.PreviewDamage(0,0,"body") && armed.SkillName(0,0)=="インシネレート","Weapon strengthens source-inspired skill and preserves its name");
        Console.WriteLine("PLAN10_ORIFLAMME_CONTENT_PASS compatible saves / growth / narrative / art");
    }
}
