using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Collections.Generic;
using NewAster.Core;
using NewAster.Data;
public static class Plan12GardenLifeTests
{
    public static void Run(Action<bool,string> check,string resources)
    {
        var options=new JsonSerializerOptions{IncludeFields=true};Func<FormalCampaignSave,string> encode=s=>JsonSerializer.Serialize(s,options);Func<string,FormalCampaignSave> decode=s=>JsonSerializer.Deserialize<FormalCampaignSave>(s,options);
        var combat=JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-shangrila.json")),options);var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-shangrila-story-content.json")),options);var home=ProductionStoryCatalog.Home(combat,story);
        var save=new FormalCampaignSave{world=new CampaignState(WorldCatalog.ColossusIds).CreateSave(),growth=new FormalGrowthSave{saveId="newaster.formal-growth",heroines=combat.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id}).ToArray()},home=FormalHomeProgress.Empty(home.contentVersion),collection=new FormalCollectionLedger{contentVersion=CollectionCatalog.ProductionVersion,materials=home.materials.Select(m=>new CollectionMaterial{id=m.id,sourceColossusId=m.colossusId,amount=100}).ToArray()}};
        save.world.unlockedGardenIds=home.gardens.Select(g=>g.id).ToArray();foreach(var d in save.world.terraform.domains){d.currentLevel=5;d.maxReachedLevel=5;}HomeConditions.Refresh(save,home);
        save.home.furnitureInstances=new[]{new HomeFurnitureInstance{instanceId="furniture.old.bench",defId="furniture.fixture.0"}};save.home.furniturePlacements=new[]{new HomePlacement{instanceId="furniture.old.bench",defId="furniture.fixture.0",gardenId=home.gardens[0].id,zoneId="zone.ground",orientationId="orientation.default",x=.25f,y=.72f}};
        save.home.occupants=new[]{new HomeOccupant{heroineId="heroine.slayer",gardenId=home.gardens[0].id,slotId="slot.idle",x=.22f,y=.7f}};save.Validate();string oldHome=JsonSerializer.Serialize(save.home,options);GardenLifeCatalog.Migrate(save);GardenLifeCatalog.Migrate(save);
        check(JsonSerializer.Serialize(save.home,options)==oldHome && save.gardenLife.assignments.Single().mode=="Fixed" && save.gardenLife.assignments.Single().gardenId==home.gardens[0].id,"Life migration preserves furniture IDs, placement and fixed resident without double migration");
        check(save.gardenLife.settings.Length==9 && save.gardenLife.settings.All(s=>s.autoLife && s.autoWeather && s.timePhase=="day") && GardenLifeCatalog.Discoveries.Length==30 && GardenLifeCatalog.Activities.Length==10,"Nine garden defaults, thirty discoveries and ten activities");
        save.gardenLife.ValidateContent(save,home);string before=encode(save);var journal=new FormalCampaignJournal(save,encode,decode);before=encode(journal.Snapshot);var request=new GardenLifeRequest("life.settings.first","settings",journal.Snapshot.revision,"night");int builds=0;
        check(journal.CommitGardenLife(request,home,s=>{builds++;s.gardenLife.Setting(home.gardens[0].id).timePhase="night";},s=>false)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"Failed life write publishes no settings changes");
        bool reject=false;try{journal.CommitGardenLife(new GardenLifeRequest("life.other","visit",0,"other"),home,s=>{},s=>true);}catch(InvalidOperationException){reject=true;}check(reject,"Other operation cannot bypass pending life save");
        check(journal.CommitGardenLife(request,home,s=>throw new Exception("Rebuilt retry"),s=>true)==GrowthCommitResult.Committed && builds==1,"Same candidate retry never repeats builder");
        var restarted=new FormalCampaignJournal(journal.Snapshot,encode,decode);check(restarted.CommitGardenLife(request,home,null,s=>throw new Exception("Duplicate write"))==GrowthCommitResult.AlreadyCommitted,"Life transaction survives restart without double applying");
        var protectedRequest=new GardenLifeRequest("life.protected","settings",restarted.Snapshot.revision,"affection");reject=false;before=encode(restarted.Snapshot);try{restarted.CommitGardenLife(protectedRequest,home,s=>s.home.affections=new[]{new HomeAffection{heroineId="heroine.slayer",value=1}},s=>true);}catch(ArgumentException){reject=true;}check(reject && encode(restarted.Snapshot)==before && !restarted.HasPending,"Life cannot change affection, formation or combat progression");
        var progress=restarted.Snapshot;foreach(var d in GardenLifeCatalog.Discoveries){
            var c=new GardenLifeContext{gardenId="garden.integrated-world",timePhase="night",weather="rain",phenomenonId="meteor",interactionTag=d.condition,partnerId="heroine.iconoclast",heroineId="heroine.slayer",furnitureId="furniture.old.bench",covered=true,sharedScenery=true,quiet=true,socialSeconds=25,asteriaCleared=true,activityId=d.condition,domains=new[]{new TerraformDomainState{domainId="life",currentLevel=5,activeExtremeId="life_water"},new TerraformDomainState{domainId="water",currentLevel=6},new TerraformDomainState{domainId="earth",currentLevel=7}}};
            if(d.condition=="morning" || d.condition=="evening")c.timePhase=d.condition;if(d.condition=="snow")c.weather="snow";if(d.condition=="aurora")c.phenomenonId="aurora";
            check(GardenLifeDiscoveries.Matches(d.condition,c),"Reachable discovery condition "+d.id);var picker=new GardenLifeDiscoveries(733);bool found=false;for(int i=0;i<6;i++)if(picker.Evaluate(d.trigger,c,progress.gardenLife).Any(x=>x.id==d.id))found=true;check(found,"Weighted discovery has a six-opportunity ceiling "+d.id);
            int inventory=progress.home.furnitureInstances.Length;GardenLifeDiscoveries.Grant(progress,d.id,"discovery."+d.condition,c);GardenLifeDiscoveries.Grant(progress,d.id,"discovery.duplicate",c);check(progress.home.furnitureInstances.Length==inventory && progress.gardenLife.records.Count(r=>r.discoveryId==d.id)==1,"Discoveries grant records/recipes only and replay is idempotent "+d.id);
        }
        check(progress.gardenLife.unlockedRecipeIds.Length==10 && progress.gardenLife.records.Length==30,"Exactly ten memorial recipes for thirty records");progress.gardenLife.ValidateContent(progress,home);
        var discoverySave=decode(before);var discoveryJournal=new FormalCampaignJournal(discoverySave,encode,decode);
        var context=progress.gardenLife.records.First().context;string discoveryId=progress.gardenLife.records.First().discoveryId;
        var discoveryTransaction=new GardenDiscoveryTransaction("life.discovery.atomic",discoveryId,context);
        var discoveryRequest=new GardenLifeRequest(discoveryTransaction.Id,"discovery",discoveryJournal.Revision,discoveryId);
        check(discoveryJournal.CommitGardenLife(discoveryRequest,home,discoveryTransaction.Apply,s=>false)==GrowthCommitResult.SaveFailed && discoveryJournal.Snapshot.gardenLife.records.Length==0,"Failed discovery save exposes neither record nor recipe");
        check(discoveryJournal.CommitGardenLife(discoveryRequest,home,s=>throw new Exception("Discovery rebuilt"),s=>true)==GrowthCommitResult.Committed && discoveryJournal.Snapshot.gardenLife.records.Single().transactionId==discoveryJournal.Snapshot.gardenLife.receipts.Last().transactionId,"Discovery record and save receipt share one durable transaction ID");
        var corrupted=decode(encode(progress));corrupted.gardenLife.records[0].context.timePhase="invalid";reject=false;try{corrupted.gardenLife.ValidateContent(corrupted,home);}catch(ArgumentException){reject=true;}check(reject,"Invalid saved discovery environment is rejected");
        check(!GardenLifeDiscoveries.Matches("cross-world",new GardenLifeContext{domains=new[]{new TerraformDomainState{domainId="life",currentLevel=5,activeExtremeId=""},new TerraformDomainState{domainId="water",currentLevel=5}}}),"Unity empty optional extreme ID cannot create a cross-world discovery");
        string beforeEventRead=encode(progress);var entries=ProductionGardenLifeCatalog.GetGardenEvents(progress,home,"heroine.slayer",home.events.First(e=>e.heroineId=="heroine.slayer").id);
        check(entries.Length==5 && entries.Any(e=>e.status=="reading") && encode(progress)==beforeEventRead,"11-3 event status bridge is read-only and preserves five authored IDs");
        var geometryFurniture=new HomeFurnitureLayout{size01=new HomePoint{x=.1f,y=.2f},drawAnchor=new HomePoint{x=.5f,y=1},footprint=new HomeRect{x=0,y=0,width=1,height=1}};
        var rotatedFootprint=HomeGeometry.Footprint(new HomePlacement{x=.5f,y=.6f,orientationId="orientation.rotate"},geometryFurniture);
        check(Math.Abs((double)(rotatedFootprint[2]*1600m)-146)<.001 && Math.Abs((double)(rotatedFootprint[3]*730m)-160)<.001,"Rotated furniture footprint preserves the actual 1600x730 pixel dimensions");
        var reservedEditor=new GardenLifeEditor(progress.home,home.gardens[0].id,home);reject=false;
        try{reservedEditor.Place(new HomePlacement{instanceId="furniture.old.bench",defId="furniture.fixture.0",gardenId=home.gardens[0].id,zoneId="zone.ground",orientationId="orientation.default",x=.54f,y=.72f});}catch(ArgumentException){reject=true;}check(reject,"Footprint touching a required route is rejected even when anchor is outside it");
        var recipe=home.furniture.Single(f=>f.id=="furniture.memorial.books");int material=HomeRules.Balance(progress,recipe.costs[0].resourceId);GardenLifeCrafting.Craft(progress,home,recipe.id,5,"craft.books");check(progress.home.furnitureInstances.Count(i=>i.defId==recipe.id)==5 && HomeRules.Balance(progress,recipe.costs[0].resourceId)==material-5*recipe.costs[0].amount,"Instant batch crafting spends exact aggregate material cost once");
        before=encode(progress);reject=false;try{GardenLifeCrafting.Craft(progress,home,recipe.id,10000,"craft.too-many");}catch(ArgumentException){reject=true;}check(reject && encode(progress)==before,"Unaffordable batch does not partially craft or spend");
        var editor=new GardenLifeEditor(progress.home,home.gardens[0].id);before=encode(progress);var moved=GardenLifeEditor.Clone(progress.home.furniturePlacements[0]);moved.x=.31f;editor.Place(moved);check(editor.UndoCount==1 && encode(progress)==before,"Furniture editing stays on a working copy");editor.Undo();check(editor.Placements[0].x==.25f,"Undo restores exact previous coordinates");editor.Redo();check(editor.Placements[0].x==.31f,"Redo restores exact candidate");editor.StoreAll();check(editor.Placements.Length==0 && editor.UndoCount==2,"Store all is one undo operation");editor.Undo();
        moved.x=.50f;reject=false;try{editor.Place(moved);}catch(ArgumentException){reject=true;}check(reject,"New placement cannot occupy required central path");moved.x=.31f;for(int i=0;i<75;i++){moved.x=.31f+i*.0001f;editor.Place(moved);}check(editor.UndoCount==50,"Undo history is bounded at fifty edits");editor.Cancel();check(editor.Placements[0].x==.25f && editor.UndoCount==0,"Cancel discards every unconfirmed edit");
        var preset=new GardenLayoutPreset{gardenId=home.gardens[0].id,index=0,items=Enumerable.Range(0,6).Select(i=>new GardenLayoutItem{furnitureDefId=recipe.id,x=.2f+i*.1f,y=.7f}).ToArray()};check(editor.Shortages(preset,progress.home)[recipe.id]==1,"Layout preview reports shortage using owned instances");reject=false;try{editor.ApplyPreset(preset,progress.home);}catch(ArgumentException){reject=true;}check(reject && encode(progress)==before,"Shortage does not auto-craft or edit stored inventory");
        var runtime=new GardenLifeRuntime(progress,home,home.gardens[0].id,821);var twin=new GardenLifeRuntime(decode(encode(progress)),home,home.gardens[0].id,821);
        check(runtime.Agents.Count==8 && runtime.Agents.Select(a=>a.personId).Distinct().Count()==8 && runtime.Agents.Any(a=>a.heroineId=="heroine.slayer") && !runtime.Agents.Any(a=>a.heroineId=="heroine.slayer-swim"),"Visible roster uses fixed residents first and excludes alternate forms of the same person");
        check(runtime.Agents.Count(a=>a.kind=="Idle")>=2 && runtime.Agents.Any(a=>a.kind!="Idle"),"Scene template begins with idle and varied existing activity");
        var kinds=new HashSet<string>();int socials=0;runtime.Trigger+=(t,c)=>{if(t=="social")socials++;};
        for(int i=0;i<1800;i++){runtime.Tick(.1f);twin.Tick(.1f);foreach(var a in runtime.Agents)kinds.Add(a.kind);if(i%100==0){check(runtime.Agents.Zip(twin.Agents,(a,b)=>a.x==b.x && a.y==b.y && a.kind==b.kind && a.tag==b.tag).All(x=>x),"Identical seed reproduces life movement and decisions");check(runtime.Agents.Count(a=>a.partnerId!=null)<=4,"At most two Social sessions run concurrently");check(runtime.Agents.Where(a=>a.slotId!=null).Select(a=>a.slotId).Distinct().Count()==runtime.Agents.Count(a=>a.slotId!=null),"Interaction slot reservations never overlap");}}
        check(kinds.Count>=4 && socials>0,"Autonomous life reaches movement, interaction and two-person Social");float x0=runtime.Agents[0].x;runtime.Paused=true;runtime.Tick(.2f);check(runtime.Agents[0].x==x0,"Viewing pause preserves current scene");runtime.Paused=false;
        foreach(var activity in GardenLifeCatalog.Activities){var type=activity.id=="hot_spring"?"garden.hot-spring":activity.id=="snow_play"?"garden.snowfield":activity.id=="water_play"?"garden.flower-water":"garden.sakura-stargazing";progress.gardenLife.Setting(type).timePhase="night";var r=new GardenLifeRuntime(progress,home,type,723);check(r.ActivityUnavailable(activity.id)==null,"Activity uses available tag-based scenery/interaction "+activity.id);r.StartActivity(activity.id);check(r.ActivityId==activity.id && r.Agents.Count<=8,"Repeatable activity has no cost and bounded participants "+activity.id);r.EndActivity();check(r.ActivityId==null && r.Agents.All(a=>a.partnerId==null),"Ending activity releases transient sessions "+activity.id);}
        var large=decode(encode(progress));large.growth.heroines=Enumerable.Range(0,256).Select(i=>new FormalHeroineGrowth{heroineId="heroine.registered-"+i}).ToArray();large.gardenLife.assignments=Array.Empty<GardenLifeAssignment>();var scale=new GardenLifeRuntime(large,home,home.gardens[0].id,1);check(scale.Agents.Count==8,"256 registered heroines simulate only eight visible agents");
        foreach(var level in new[]{5,6,7}){foreach(var d in progress.world.terraform.domains)d.currentLevel=level;var r=new GardenLifeRuntime(progress,home,"garden.integrated-world",3);check(r.Agents.Count>0 && progress.home.furnitureInstances.Length==6,"Terraform level "+level+" retains livable scenery and furniture");}
        string persisted=encode(progress);check(!persisted.Contains("recentActions") && !persisted.Contains("socialState") && !persisted.Contains("SceneTemplate") && !persisted.Contains("Paused"),"Runtime life state is excluded from persistence");
    }
}
