using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
internal static class Plan10ShangrilaTests {
 public static void Run(Action<bool,string> check,string resources){
  var options=new JsonSerializerOptions{IncludeFields=true};Func<CombatDefinitionCatalog> read=()=>JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-shangrila.json")),options);var c=read();c.Validate();
  check(c.HeroineIds.Length==15 && c.HeroineIds.Select(c.PersonId).Distinct().Count()==12 && c.jobs.Length==13,"All thirteen jobs and fifteen forms of twelve people");
  Func<int,PlayableBattle> fixture=slot=>{var defs=read();foreach(var j in defs.jobs){j.hp=100000;j.speed=100;}foreach(var s in defs.skills)s.chainEligible=false;var ids=defs.FormationIds;ids[slot]="heroine.shangrila";var enemy=ColossusCombatCatalog.Get(WorldCatalog.ColossusIds[0]);enemy.baseHp=10000000;enemy.hpPerLevel=1;enemy.enemySpeed=1;enemy.baseDamage=1;enemy.statusResistances=Array.Empty<EnemyStatusResistanceDef>();return new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:defs.WithFormation(ids),colossusDefinition:enemy,useJobRulesV2:true,deployment:new BattleDeployment(null,new[]{new HomeSniperSupport{heroineId="heroine.shangrila",targetId=ids[(slot+1)%5]}}));};
  Action<PlayableBattle,int> ready=(b,a)=>{int limit=0;while(b.AvailableHero!=a && !b.Ended && limit++<500)b.Pass();check(b.AvailableHero==a,"Actor reaches READY");};
  for(int i=0;i<5;i++){
   var b=fixture(i);ready(b,i);int hp=b.State.Heroes[i].HitPoints,maxHp=b.State.Heroes[i].MaxHitPoints;check(b.SniperSupportTarget(i)==(i+1)%5,"Saved support applies in every formation position");check(b.Act(i,0,"body") && b.State.Heroes[i].HitPoints==hp-maxHp/5 && b.State.Heroes[i].JobResource==3,"First source shot has exact 20% recoil and command gauge+3");
   int ally=(i+1)%5;ready(b,ally);if(b.JobState(ally).Id=="job.blaster"){b.State.Heroes[ally].GainResource(4);b.SelectBlaster(ally,0,1);}long next=b.NextAt(i);int gauge=b.State.Heroes[i].JobResource;b.DrainPresentationEvents();check(b.Act(ally,0,"body"),"Supported ally attacks");check(b.DrainPresentationEvents().Count(e=>e.Actor==i && e.Kind==BattlePresentationKind.Attack && e.Message.Contains("支援射撃"))==1 && b.NextAt(i)==next && b.State.Heroes[i].JobResource==gauge,"One nonrecursive support consumes no sniper gauge or normal WT");
  }
  var other=fixture(0);ready(other,2);other.DrainPresentationEvents();check(other.Act(2,0,"body") && !other.DrainPresentationEvents().Any(e=>e.Actor==0 && e.Message.Contains("支援射撃")),"Ordinary support never covers a different ally");
  var healing=fixture(0);ready(healing,0);healing.State.Heroes[0].TakeDamage(1000);int wounded=healing.State.Heroes[0].HitPoints;check(healing.Act(0,1,"body") && healing.State.Heroes[0].HitPoints==wounded+healing.State.Heroes[0].BaseAttack*45/100 && healing.State.BossStatus.Meter("bleed")==30,"Second source shot heals from base attack and accumulates bleed");
  var ultimate=fixture(0);ready(ultimate,0);int hp0=ultimate.State.Heroes[0].HitPoints;check(ultimate.Act(0,2,"body") && ultimate.State.Heroes[0].HitPoints==hp0-ultimate.State.Heroes[0].MaxHitPoints*40/100 && ultimate.State.Heroes[0].TimedEffects.Any(e=>e.Kind=="attack-reduction" && e.Percent==35 && e.RemainingCommands==2),"Source ultimate has 40% recoil and 35% attack penalty");check(HeroineSkillRules.AtLevel(c.Skill("heroine.shangrila",2),7).selfEffects.Single().percent==35,"Upgrading never increases own attack penalty");
  var cast=fixture(0);ready(cast,0);long clock=cast.Clock;check(!cast.StartSniperMode(0,"body") && cast.Clock==clock,"Non-MAX mode refuses atomically");cast.State.Heroes[0].GainResource(15);check(!cast.StartSniperMode(0,"missing") && cast.State.Heroes[0].JobResource==15 && cast.Clock==clock,"Invalid mode target does not spend");check(cast.StartSniperMode(0,"body") && cast.IsSniping(0) && cast.State.Heroes[0].JobResource==0,"Mode spends MAX once and holds a cast");cast.DrainPresentationEvents();ready(cast,2);check(cast.Act(2,0,"body") && cast.DrainPresentationEvents().Count(e=>e.Actor==0 && e.Message.Contains("支援射撃"))==1,"Casting supports an ally beyond the saved ordinary target");int guard=0;while(cast.IsSniping(0) && guard++<200)cast.Pass();check(!cast.IsSniping(0) && cast.DrainPresentationEvents().Any(e=>e.Actor==0 && e.Kind==BattlePresentationKind.CastRelease) && cast.SniperSupportTarget(0)==1,"Mode releases once and restores ordinary support target");
  var missing=fixture(0);ready(missing,0);string part=missing.State.Parts.First(p=>!p.IsBroken).Id;missing.State.Heroes[0].GainResource(15);check(missing.StartSniperMode(0,part),"Part-targeted mode begins");missing.State.BreakPart(part,int.MaxValue);missing.DrainPresentationEvents();guard=0;while(missing.IsSniping(0) && guard++<200)missing.Pass();check(!missing.IsSniping(0) && missing.DrainPresentationEvents().Any(e=>e.Kind==BattlePresentationKind.CastCanceled) && missing.State.Heroes[0].JobResource==0,"Lost part cancels without refund or retarget");
  foreach(string reason in new[]{"death","stun","absent"}){var canceled=fixture(0);ready(canceled,0);canceled.State.Heroes[0].GainResource(15);canceled.StartSniperMode(0,"body");if(reason=="death")canceled.State.Heroes[0].TakeDamage(int.MaxValue);else canceled.State.Heroes[0].AddStatus(new EnemyStatusDef{kind=reason,amount=100});canceled.DrainPresentationEvents();canceled.Pass();check(!canceled.IsSniping(0) && canceled.DrainPresentationEvents().Any(e=>e.Actor==0 && e.Kind==BattlePresentationKind.CastCanceled),"Cast interruption: "+reason);}
  var original=new HomeSniperSupport{heroineId="heroine.shangrila",targetId=c.FormationIds[1]};var deployment=new BattleDeployment(null,new[]{original});original.targetId="changed";var leaked=deployment.SniperSupports;leaked[0].targetId="changed-again";check(deployment.SniperSupports[0].targetId==c.FormationIds[1],"Deployment defensively copies mutable support entries");
  if(Environment.GetEnvironmentVariable("NEWASTER_PLAN10_SHANGRILA_ART")=="1"){
   var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-shangrila-story-content.json")),options);story.Validate(c.HeroineIds,WorldCatalog.ColossusIds.ToArray());var home=ProductionStoryCatalog.Home(c,story);home.Validate(true);check(home.weaponNodes.Count(n=>n.heroineId=="heroine.shangrila")==13 && home.assets.All(a=>!a.placeholder),"Sniper dedicated art and independent weapon tree");check(story.chapters.Where(x=>x.ownerId=="heroine.shangrila").Sum(x=>x.pages.Length)==30 && story.events.Count(e=>e.ownerId=="heroine.shangrila")==5,"Sniper thirty original pages and five relationship events");Plan10FormContinuityTests.Run(check,c,story,options);
  }
  Console.WriteLine("PLAN10_SHANGRILA_PASS selected support / all positions / cast release and cancellation / source recoil and heal");
 }
}
