using System;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
public static class Plan6ExperienceTests
{
    public static void Run(Action<bool,string> check,CombatDefinitionCatalog combat)
    {
        var options=new JsonSerializerOptions{IncludeFields=true};Func<FormalCampaignSave,string> encode=s=>JsonSerializer.Serialize(s,options);Func<string,FormalCampaignSave> decode=s=>JsonSerializer.Deserialize<FormalCampaignSave>(s,options);
        var c=HomeExperienceFixture.Create(combat);var material=c.materials[0];var s=new FormalCampaignSave{world=new CampaignState(WorldCatalog.ColossusIds).CreateSave(),growth=new FormalGrowthSave{saveId="newaster.formal-growth",heroines=combat.FormationIds.Select(id=>new FormalHeroineGrowth{heroineId=id}).ToArray()},collection=new FormalCollectionLedger{materials=new[]{new CollectionMaterial{id=material.id,sourceColossusId=material.colossusId,amount=100}}}};
        var journal=new FormalCampaignJournal(s,encode,decode);
        Func<HomeOperation,FormalHomeRequest> request=op=>new FormalHomeRequest(Guid.NewGuid().ToString("N"),op.Kind=="equip"?"weapon":op.Kind=="remove"?"place":op.Kind=="use"?"occupant":op.Kind,journal.Snapshot.revision,c.contentVersion,op.Key);
        Action<HomeOperation> commit=op=>check(journal.CommitHomeOperation(request(op),c,op,n=>true)==GrowthCommitResult.Committed,"home operation "+op.Kind);
        Action<Action,string> reject=(a,label)=>{bool failed=false;try{a();}catch(Exception e)when(e is ArgumentException || e is InvalidOperationException || e is OverflowException){failed=true;}check(failed,label);};
        check(new HomeOperation("craft","a/b","c").Key!=new HomeOperation("craft","a","b/c").Key,"payload delimiters cannot collide");
        foreach(var hero in combat.FormationIds){var nodes=c.weaponNodes.Where(n=>n.heroineId==hero).ToArray();reject(()=>commit(new HomeOperation("weapon",nodes[3].id)),"all parents required");commit(new HomeOperation("weapon",nodes[0].id));commit(new HomeOperation("weapon",nodes[1].id));commit(new HomeOperation("weapon",nodes[2].id));commit(new HomeOperation("weapon",nodes[3].id));commit(new HomeOperation("equip",nodes[3].id,hero));}
        check(HomeRules.Balance(journal.Snapshot,material.id)==40,"all five trees spend 60 materials");
        var same=new HomeOperation("weapon",c.weaponNodes[3].id);commit(same);check(HomeRules.Balance(journal.Snapshot,material.id)==40,"acquired node costs nothing");
        var before=new PlayableBattle(1,new PlayableProgress(),combatDefinitions:combat,formalGrowth:journal.Snapshot.growth);
        var after=new PlayableBattle(1,new PlayableProgress(),combatDefinitions:combat,formalGrowth:journal.Snapshot.growth,homeProgress:journal.Snapshot.home,homeCatalog:c);
        check(after.State.Heroes[0].Attack>before.State.Heroes[0].Attack && after.SkillName(0,0).Contains("γ"),"next battle applies equipped ability and skill");check(after.State.Heroes[0].Speed==before.State.Heroes[0].Speed && after.ChainRate(0)==before.ChainRate(0),"equipment preserves speed and chain");
        var unequip=new HomeOperation("equip","unequip",combat.FormationIds[0]);var retry=request(unequip);string old=encode(journal.Snapshot);check(journal.CommitHomeOperation(retry,c,unequip,n=>false)==GrowthCommitResult.SaveFailed && old==encode(journal.Snapshot),"weapon save failure leaves whole snapshot unchanged");reject(()=>commit(new HomeOperation("talk",combat.FormationIds[0])),"pending excludes different operation");check(journal.CommitHomeOperation(retry,c,unequip,n=>true)==GrowthCommitResult.Committed,"frozen weapon retry");check(journal.CommitHomeOperation(retry,c,unequip,n=>false)==GrowthCommitResult.AlreadyCommitted,"same receipt idempotent");
        // Unlock test gardens through the existing world boundary, without granting production progress.
        var world=journal.Snapshot.world;world.unlockedGardenIds=c.gardens.Take(2).Select(g=>g.id).ToArray();check(journal.CommitWorld(world,n=>true),"fixture garden unlock");
        commit(new HomeOperation("craft",c.furniture[0].id,"instance.a"));commit(new HomeOperation("craft",c.furniture[1].id,"instance.b"));string garden=c.gardens[0].id;
        commit(new HomeOperation("place","instance.a",garden:garden,zone:"zone.ground",x:.3f,y:.6f));
        reject(()=>commit(new HomeOperation("place","instance.b",garden:garden,zone:"zone.ground",x:.3f,y:.6f)),"positive area overlap rejected");
        commit(new HomeOperation("place","instance.b",garden:garden,zone:"zone.ground",x:.428f,y:.6f));check(journal.Snapshot.home.furniturePlacements.Length==2,"edge contact permitted");
        reject(()=>commit(new HomeOperation("place","instance.b",garden:garden,zone:"zone.ground",x:0,y:.6f)),"whole footprint must be in bounds");reject(()=>new HomeOperation("place","instance.b",x:float.NaN),"nonfinite coordinate rejected");
        commit(new HomeOperation("occupant",combat.FormationIds[0],garden:garden,x:.3f,y:.6f));commit(new HomeOperation("occupant",combat.FormationIds[0],garden:c.gardens[1].id,x:.5f,y:.7f));check(journal.Snapshot.home.occupants.Length==1 && journal.Snapshot.home.occupants[0].gardenId==c.gardens[1].id,"garden move retains one heroine across all gardens");
        commit(new HomeOperation("occupant",combat.FormationIds[0],garden:garden,x:.5f,y:.7f));commit(new HomeOperation("use",combat.FormationIds[0],"instance.a"));check(journal.Snapshot.home.occupants[0].furnitureInstanceId==null,"missing SD action returns idle");
        c.assets.Single(a=>a.id==c.furniture[0].assetId).placeholder=false;commit(new HomeOperation("use",combat.FormationIds[0],"instance.a"));check(journal.Snapshot.home.occupants[0].actionId=="action.sit" && Math.Abs(journal.Snapshot.home.occupants[0].y-.56f)<.00001,"supported furniture use attaches to authored slot offset");commit(new HomeOperation("talk",combat.FormationIds[0]));check(journal.Snapshot.home.occupants[0].actionId==null,"conversation returns supported action to idle");commit(new HomeOperation("use",combat.FormationIds[0],"instance.a"));commit(new HomeOperation("place","instance.a",garden:garden,zone:"zone.ground",x:.3f,y:.6f));check(journal.Snapshot.home.occupants[0].actionId==null,"furniture movement clears use reference");c.assets.Single(a=>a.id==c.furniture[0].assetId).placeholder=true;
        commit(new HomeOperation("remove","instance.a"));check(journal.Snapshot.home.furnitureInstances.Length==2 && journal.Snapshot.home.furniturePlacements.Length==1,"remove retains owned individual");
        commit(new HomeOperation("place","instance.a",garden:garden,zone:"zone.ground",x:.3f,y:.6f));c.assets.Single(a=>a.id==c.furniture[0].assetId).placeholder=false;commit(new HomeOperation("use",combat.FormationIds[0],"instance.a"));commit(new HomeOperation("occupant",combat.FormationIds[1],garden:garden,x:.5f,y:.6f));commit(new HomeOperation("use",combat.FormationIds[1],"instance.a"));check(journal.Snapshot.home.occupants.Single(o=>o.heroineId==combat.FormationIds[1]).actionId==null,"occupied slot gracefully falls back to idle");commit(new HomeOperation("remove","instance.a"));check(journal.Snapshot.home.occupants.All(o=>o.furnitureInstanceId==null),"removal detaches active furniture users");c.assets.Single(a=>a.id==c.furniture[0].assetId).placeholder=true;
        var restored=decode(encode(journal.Snapshot));restored.home.ValidateContent(c,restored);check(restored.home.furniturePlacements[0].x==.428f,"placement survives JSON with same decision");
        commit(new HomeOperation("talk",combat.FormationIds[0]));check(journal.Snapshot.home.affections[0].value==2 && journal.Snapshot.home.unlockedEventIds.Contains(c.events[0].id) && !journal.Snapshot.home.loverHeroineIds.Any(),"affection unlock distinct from reading and lover");
        var ev=c.events[0];ev.rewards=new[]{new HomeCost{resourceId=material.id,amount=2}};
        var session=new AdvSession(c,ev.sceneId,ev.id,false,journal.Snapshot.home.readLineKeys);check(session.Actors.Count==2 && session.Actors[1].PosePlaceholder && session.Actors[1].ExpressionAsset==c.displays[1].expressions[0].assetId,"two actors and same-outfit normal fallback");session.Tick(.3);check(!session.FullyVisible && !session.NewlyRead.Any(),"partial text is not read");session.Advance();check(session.FullyVisible && !session.NewlyRead.Any(),"first input reveals only");session.Advance();check(session.CgId!=null && session.HideActors && session.Actors.Count==2 && session.NewlyRead.Count==1,"next input marks line and CG retains actor state");
        var line=session.NewlyRead[0];var lineRequest=new FormalHomeRequest("line.tx","advRead",journal.Snapshot.revision,c.contentVersion,line.sceneId+"/"+line.scriptVersion+"/"+line.lineId);
        check(journal.CommitAdvLine(lineRequest,c,line,n=>true)==GrowthCommitResult.Committed && !journal.Snapshot.home.readEventIds.Any(),"interruption saves only advanced line");
        var restart=new AdvSession(c,ev.sceneId,ev.id,false,journal.Snapshot.home.readLineKeys);check(restart.LineId=="line.one" && restart.Backlog.Count==1,"restart starts at scene beginning");restart.Tick(.3);restart.SetSkip(true);restart.Tick(.1);check(restart.LineId=="line.long" && !restart.Skip,"skip stops first unread after executing CG");
        string partial=restart.VisibleText;restart.SetAuto(true);restart.Pause();for(int i=0;i<100;i++)restart.Tick(.5);check(restart.VisibleText==partial && !restart.Auto && restart.Paused,"inactive/backlog pause timers and reset auto");restart.Resume();restart.Tick(10);check(restart.VisibleText==partial,"resume cannot catch up elapsed time");restart.Advance();restart.Advance();check(restart.CgId==null && !restart.HideActors && restart.Actors.Count==1 && restart.Actors[0].SlotId=="slot.center","hide CG restores actors and actor updates move without duplicates");
        foreach(int speed in new[]{15,30,60,120}){restart.SetSpeed(speed);check(restart.CharactersPerSecond==speed,"text speed supported "+speed);}restart.Advance();restart.Advance();check(restart.EndReached && !restart.Completed,"end awaits durable completion");
        foreach(var l in restart.NewlyRead){var r=new FormalHomeRequest(Guid.NewGuid().ToString("N"),"advRead",journal.Snapshot.revision,c.contentVersion,l.sceneId+"/"+l.scriptVersion+"/"+l.lineId);check(journal.CommitAdvLine(r,c,l,n=>true)==GrowthCommitResult.Committed,"remaining read line persists");}
        int rewardBefore=HomeRules.Balance(journal.Snapshot,material.id);var end=new FormalHomeRequest("end.tx","sceneEnd",journal.Snapshot.revision,c.contentVersion,restart.SourceId+"/"+restart.SceneId+"/"+restart.ScriptVersion);old=encode(journal.Snapshot);check(journal.CommitAdvEnd(end,c,restart,n=>false)==GrowthCommitResult.SaveFailed && old==encode(journal.Snapshot) && !restart.Completed,"end failure freezes read reward lover and unlocks");check(journal.CommitAdvEnd(end,c,restart,n=>true)==GrowthCommitResult.Committed,"same end candidate retry");restart.MarkCommitted();check(journal.Snapshot.home.readEventIds.Contains(ev.id) && journal.Snapshot.home.unlockedEventIds.Contains(c.events[1].id) && HomeRules.Balance(journal.Snapshot,material.id)==rewardBefore+2,"read-event unlock and first reward atomic");check(journal.CommitAdvEnd(end,c,restart,n=>false)==GrowthCommitResult.AlreadyCommitted,"end ID repeated without reward");
        var replay=new AdvSession(c,ev.sceneId,ev.id,true,journal.Snapshot.home.readLineKeys);old=encode(journal.Snapshot);replay.Tick(.3);while(!replay.EndReached){replay.Advance();replay.Advance();}replay.MarkCommitted();check(!replay.NewlyRead.Any() && old==encode(journal.Snapshot),"all replay commands fully read-only");reject(()=>journal.CommitAdvEnd(end,c,replay,n=>true),"replay cannot commit end");
        foreach(var eventDef in c.events.Take(3).Skip(1)){var run=new AdvSession(c,eventDef.sceneId,eventDef.id,false,journal.Snapshot.home.readLineKeys);run.Tick(.3);while(!run.EndReached){run.Advance();run.Advance();}var r=new FormalHomeRequest(Guid.NewGuid().ToString("N"),"sceneEnd",journal.Snapshot.revision,c.contentVersion,run.SourceId+"/"+run.SceneId+"/"+run.ScriptVersion);check(journal.CommitAdvEnd(r,c,run,n=>true)==GrowthCommitResult.Committed,"explicit affinity completion");}
        check(journal.Snapshot.home.loverHeroineIds.Contains(combat.FormationIds[0]) && journal.Snapshot.home.unlockedEventIds.Contains(c.events[3].id),"explicit completed affinity event establishes lover");
        var versioned=HomeExperienceFixture.Create(combat);versioned.events[0].rewards=ev.rewards;versioned.scripts.Single(sc=>sc.id==ev.sceneId).scriptVersion=2;var revised=new AdvSession(versioned,ev.sceneId,ev.id,false,journal.Snapshot.home.readLineKeys);revised.Tick(.3);revised.SetSkip(true);check(!revised.Skip,"changed script version does not inherit read keys");journal.Snapshot.home.ValidateContent(versioned,journal.Snapshot);
        check(HomeConditions.Evaluate(new HomeCondition{kind="all",items=new[]{new HomeCondition{kind="flag",domain="eventRead",id=ev.id},new HomeCondition{kind="atLeast",domain="affection",ownerId=combat.FormationIds[0],value=1}}},journal.Snapshot),"condition evaluates one snapshot");reject(()=>HomeConditions.Evaluate(new HomeCondition{kind="any"},journal.Snapshot),"empty any rejected");
        var insufficient=journal.Snapshot;insufficient.collection.materials[0].amount=0;var poor=new FormalCampaignJournal(insufficient,encode,decode);var craft=new HomeOperation("craft",c.furniture[0].id,"poor.instance");var poorRequest=new FormalHomeRequest("poor.tx","craft",poor.Snapshot.revision,c.contentVersion,craft.Key);old=encode(poor.Snapshot);reject(()=>poor.CommitHomeOperation(poorRequest,c,craft,n=>true),"insufficient crafting materials rejected");check(old==encode(poor.Snapshot) && !poor.HasPending,"insufficient operation changes no state or receipt");
        var invalid=c.furniture[0];float size=invalid.size01.x;invalid.size01.x=0;reject(()=>c.Validate(),"nonpositive geometry rejected before use");invalid.size01.x=size;
        var corrupt=journal.Snapshot;corrupt.home.furniturePlacements[0].x=0;reject(()=>corrupt.home.ValidateContent(c,corrupt),"invalid saved footprint rejected on content binding");
        string source=c.chapters[0].id;var chapter=c.chapters[0];var poems=journal.Snapshot;poems.world.poemIds=poems.world.poemIds.Union(chapter.requiredPoemIds).ToArray();HomeConditions.Refresh(poems,c);check(poems.world.unlockedStoryIds.Contains(source),"main chapter unlocked only from poems without event dependency");
        var domains=journal.Snapshot;check(HomeConditions.Evaluate(new HomeCondition{kind="flag",domain="heroineOwned",id=combat.FormationIds[0]},domains) && HomeConditions.Evaluate(new HomeCondition{kind="flag",domain="lover",id=combat.FormationIds[0]},domains) && HomeConditions.Evaluate(new HomeCondition{kind="atLeast",domain="terraformingXp",value=0},domains),"independent flag and quantity domains");
        var talkPack=HomeExperienceFixture.Create(combat);talkPack.interactions[0].costs=null;reject(()=>talkPack.Validate(),"unresolved interaction cost blocks adoption");
    }
}
