using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
public static class Plan14OopartTests
{
    public static void Run(Action<bool,string> check,string resources)
    {
        var json=new JsonSerializerOptions{IncludeFields=true};Func<FormalCampaignSave,string> encode=s=>JsonSerializer.Serialize(s,json);Func<string,FormalCampaignSave> decode=s=>JsonSerializer.Deserialize<FormalCampaignSave>(s,json);
        var combat=JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-shangrila.json")),json);var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-shangrila-story-content.json")),json);var catalog=ProductionStoryCatalog.Collection(combat,story);var home=ProductionStoryCatalog.Home(combat,story);catalog.Validate();
        Action<Action,string> reject=(f,message)=>{bool bad=false;try{f();}catch(Exception e)when(e is ArgumentException || e is InvalidOperationException){bad=true;}check(bad,message);};
        Func<FormalCampaignSave> fresh=()=>{var s=new FormalCampaignSave{world=new CampaignState(WorldCatalog.ColossusIds).CreateSave(),growth=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=300000,heroines=combat.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=30}).ToArray()},home=FormalHomeProgress.Empty(home.contentVersion),collection=new FormalCollectionLedger{contentVersion=catalog.contentVersion,relics=catalog.relics.Select(r=>new CollectionRelic{id=r.id,contentVersion=catalog.contentVersion}).ToArray(),materials=catalog.resources.Where(r=>r.kind=="material").Select(r=>new CollectionMaterial{id=r.id,sourceColossusId=r.ownerId,amount=10000}).ToArray()}};s.home.formationIds=combat.FormationIds;OopartSaveAdapter.Migrate(s.collection,catalog,s.home.formationIds);return s;};
        Func<FormalCampaignSave,CombatDefinitionCatalog,PanzerLoadout,PlayableBattle> battle=(s,c,p)=>new PlayableBattle(50,new PlayableProgress(),1137,combatDefinitions:c,formalGrowth:s.growth,collectionGrowth:s.collection,homeProgress:s.home,homeCatalog:home,relicCatalog:catalog,useJobRulesV2:true,panzerLoadout:p,deployment:s.home.Deployment(c.FormationIds));
        Action<PlayableBattle,int> ready=(b,actor)=>{int guard=0;while(b.AvailableHero!=actor && !b.Ended && guard++<200){if(b.AvailableHero>=0 && b.RequiresPanzerDefense(b.AvailableHero))b.DefendPanzer(b.AvailableHero);else b.Pass();}check(b.AvailableHero==actor,"OP actor reaches a legal READY window");};
        string legacyJson="{\"collection\":{\"name\":\"brace } [\",\"ooparts\":{\"version\":1}},\"growth\":{\"nectar\":7}}";
        string collectionJson=FormalCampaignJsonShape.RootMemberJson(legacyJson,"collection");check(collectionJson.Contains("brace } [") && FormalCampaignJsonShape.RootInt32Member(FormalCampaignJsonShape.RootMemberJson(legacyJson,"growth"),"nectar")==7,"OP-18 nested JSON extraction respects quoted brackets and sibling fields");
        string absent=FormalCampaignJsonShape.WithRootMemberJson(legacyJson,"collection",FormalCampaignJsonShape.WithNullRootMember(collectionJson,"ooparts"));check(FormalCampaignJsonShape.RootMemberIsNull(FormalCampaignJsonShape.RootMemberJson(absent,"collection"),"ooparts") && absent.Contains("nectar"),"OP-18 Unity nested null preservation keeps unrelated root members");
        var save=fresh();var d=catalog.Oopart("relic.tactic.skill-two");var o=save.collection.ooparts;var p=o.progress.Single(x=>x.oopartId==d.id);p.level=7;
        var incoming=new StatValues{hp=200,attack=50,physicalDefense=40,magicDefense=60,speed=8};OopartService.Merge(o,d,incoming);OopartService.Equip(o,0,d.id);OopartService.Merge(o,d,new StatValues{hp=100,attack=80,physicalDefense=20,magicDefense=70,speed=4});
        check(o.progress.Count(x=>x.oopartId==d.id)==1 && p.level==7 && o.slots[0].equippedOopartId==d.id,"OP-01 same-name acquisition preserves one inventory entry, level and equipment");check(p.accumulatedRandomStats.hp==200 && p.accumulatedRandomStats.attack==80 && p.accumulatedRandomStats.physicalDefense==40 && p.accumulatedRandomStats.magicDefense==70 && p.accumulatedRandomStats.speed==8,"OP-02 independent component maxima never lower any random stat");
        for(int seed=0;seed<40;seed++){var roll=OopartService.Roll(d,new Random(seed));check(d.randomStats.All(r=>roll.Get(r.stat)>=(r.maximum+4)/5 && roll.Get(r.stat)<=r.maximum),"OP-02 all five independent rolls remain within authored 20..100% bounds");}
        string original=o.slots[0].heroineFormId;o.SyncFormation(combat.FormationIds.Reverse().ToArray());check(o.slots[0].heroineFormId!=original && o.slots[0].equippedOopartId==d.id,"OP-03 equipped oopart stays in the slot when people swap");o.slots[0].heroineFormId=null;check(o.slots[0].equippedOopartId==d.id,"OP-03 empty slot retains equipment");reject(()=>OopartService.Equip(o,1,d.id),"OP-04 duplicate equipment in the same formation is rejected");OopartService.SavePreset(o,"preset.a","A");OopartService.Equip(o,0,null);OopartService.Equip(o,1,d.id);OopartService.SavePreset(o,"preset.b","B");OopartService.LoadPreset(o,"preset.a");check(o.slots[0].equippedOopartId==d.id && o.presets[1].slots[1].equippedOopartId==d.id,"OP-04 different presets may refer to the same owned oopart");
        var tools=catalog.Oopart("relic.tactic.tools");var context=new OopartEffectContext{jobId="job.fighter"};check(OopartEffectEngine.Value(tools.effects[0],context)==0 && OopartEffectEngine.Value(tools.effects[1],context)==20,"OP-05 mismatched job disables only its own effect");context.inBattle=false;var wounded=catalog.Oopart("relic.tactic.wounded");check(OopartEffectEngine.Active(wounded.effects[1],context)==null,"OP-05 HP-dependent conditions remain deferred outside combat");var support=catalog.Oopart("relic.tactic.support");context.jobId="job.artist";check(OopartEffectEngine.Active(support.effects[0],context)==true,"OP-05 nested OR condition supports artist or general");
        save=fresh();OopartService.Equip(save.collection.ooparts,0,d.id);var b=battle(save,combat,null);var h=b.State.Heroes[0];int baseAttack=h.BaseAttack;
        h.ApplyOopartBuffs(new[]{new TimedSelfEffectDef{kind="attack",percent=30,turns=3}},"actor.a","skill.a",20);h.ApplyOopartBuffs(new[]{new TimedSelfEffectDef{kind="attack",percent=20,turns=3}},"actor.b","skill.b",0);check(h.Attack==baseAttack*156/100,"OP-06 source A is strengthened to36 then added to source B20 without multiplication");check(h.OopartBuffs.Count==2 && h.OopartBuffs.Any(v=>v.sourceActorId=="actor.a" && v.value==36),"OP-06 separate buff instances retain source actor and amount");
        save=fresh();OopartService.Equip(save.collection.ooparts,0,"relic.tactic.wounded");b=battle(save,combat,null);h=b.State.Heroes[0];int full=h.Attack;h.TakeDamage(h.MaxHitPoints/2);check(h.Attack>full,"OP-07 changing HP re-evaluates attack without waiting for a turn");h.Heal(h.MaxHitPoints);check(h.Attack==full,"OP-07 healing removes the missing-HP bonus");
        save=fresh();OopartService.Equip(save.collection.ooparts,0,"relic.tactic.hit-shell");b=battle(save,combat,null);h=b.State.Heroes[0];int guardDefense=h.PhysicalDefense;h.RegisterOopartHit("action.a");h.RegisterOopartHit("action.a");check(h.OopartHitCount==1 && h.PhysicalDefense>guardDefense,"OP-07 multi-hit action counts at most once");h.RegisterOopartHit("action.b");check(h.OopartHitCount==2,"OP-07 a different attack increments the hit counter");
        var growth=catalog.Oopart("relic.special.ramp").effects[0];context=new OopartEffectContext{clock=100};check(OopartEffectEngine.Value(growth,context)==5,"OP-07 logical100 is exactly one elapsed turn");context.clock=10000;check(OopartEffectEngine.Value(growth,context)==20,"OP-07 turn growth stops at20%");
        save=fresh();OopartService.Equip(save.collection.ooparts,0,"relic.tactic.stun");b=battle(save,combat,null);check(OopartEffectEngine.Value(catalog.Oopart("relic.tactic.stun").effects[0],new OopartEffectContext())+30==50,"OP-08 status enhancement is fixed+20 rather than a percent multiplier");check(catalog.oopartDefs.Count(x=>x.effects.Any(e=>e.effectType=="status" && e.targetId=="stun"))==1,"OP-08 only one authored control-status item exists");
        var statusCombat=combat.WithFormation(combat.FormationIds);var statusSkill=statusCombat.skills.Single(x=>x.id==statusCombat.Hero(statusCombat.FormationIds[0]).skills[0]);statusSkill.statusEffects=new[]{new EnemyStatusDef{kind="stun",amount=30}};statusCombat.enemyStatusResistances=new[]{new EnemyStatusResistanceDef{kind="stun",resistanceBp=5000}};
        save=fresh();OopartService.Equip(save.collection.ooparts,0,"relic.tactic.stun");b=battle(save,statusCombat,null);ready(b,0);b.State.Heroes[0].GainResource(100);check(b.Act(0,0,"body") && b.State.EnemyStatus("body").Meter("stun")==25,"OP-08 real attack applies (30+20) with existing50% resistance instead of bypassing it");
        statusCombat.enemyStatusResistances[0].resistanceBp=10000;b=battle(save,statusCombat,null);ready(b,0);b.State.Heroes[0].GainResource(100);check(b.Act(0,0,"body") && b.State.EnemyStatus("body").Meter("stun")==0 && !b.State.EnemyStatus("body").Active("stun"),"OP-08 full resistance remains effective despite fixed status boost");
        var castFormation=combat.FormationIds.ToArray();castFormation[0]="heroine.echidna";int originalEchidna=Array.IndexOf(castFormation,"heroine.echidna",1);if(originalEchidna>=0)castFormation[originalEchidna]="heroine.slayer";var caster=combat.WithFormation(castFormation);save=fresh();save.home.formationIds=castFormation;save.collection.ooparts.SyncFormation(castFormation);var ordinary=battle(save,caster,null);OopartService.Equip(save.collection.ooparts,0,"relic.tactic.quick-cast");b=battle(save,caster,null);check(b.CastDelay(0,1)<ordinary.CastDelay(0,1) && b.RecoveryDelay(0,1)<ordinary.RecoveryDelay(0,1),"OP-09 cast WT percent and action WT fixed subtraction affect committed timing");
        var generals=combat.FormationIds.ToArray();generals[0]="heroine.slayer-swim";var commanded=combat.WithFormation(generals);save=fresh();save.home.formationIds=generals;save.home.commanderHeroineId=generals[0];save.collection.ooparts.SyncFormation(generals);ordinary=battle(save,commanded,null);OopartService.Equip(save.collection.ooparts,0,"relic.job.general.affinity");b=battle(save,commanded,null);for(int i=0;i<5;i++)check(b.State.Heroes[i].GeneralAttackPercent==ordinary.State.Heroes[i].GeneralAttackPercent*120/100 && b.State.Heroes[i].GeneralPhysicalDefensePercent==ordinary.State.Heroes[i].GeneralPhysicalDefensePercent*120/100,"OP-10 source general buff boosts authored slot values without changing target slots");
        var artists=combat.FormationIds.ToArray();artists[0]="heroine.r";var singing=combat.WithFormation(artists);save=fresh();save.home.formationIds=artists;save.collection.ooparts.SyncFormation(artists);OopartService.Equip(save.collection.ooparts,0,"relic.job.artist.affinity");b=battle(save,singing,null);ready(b,0);b.State.Heroes[0].GainResource(100);check(b.StartSong(0),"OP-11 artist starts a legal song");int gauge=b.State.Heroes[0].JobResource;b.State.Heroes[0].GainResource(20);check(b.JobState(0).Singing && b.State.Heroes[0].JobResource==gauge && !b.ConditionsSatisfied(0,0),"OP-11 singing blocks all resource gain and ordinary skills despite oopart bonuses");
        var tanks=combat.FormationIds.ToArray();tanks[0]="heroine.shell";var tank=combat.WithFormation(tanks);tank.jobs.Single(j=>j.id=="job.panzer").speed=200;save=fresh();save.home.formationIds=tanks;save.collection.ooparts.SyncFormation(tanks);OopartService.Equip(save.collection.ooparts,0,"relic.job.panzer.affinity");OopartService.Equip(save.collection.ooparts,1,"relic.tactic.first-flame");b=battle(save,tank,new PanzerLoadout("physical","extend","guard"));ready(b,0);check(b.JobState(0).ToolUses.SequenceEqual(new[]{3,3}),"OP-12 oopart raises tool maximums once at battle start");var early=b.State.Heroes[1].OopartBuffs.Single(v=>v.sourceId=="first.attack");check(early.value==72 && early.expiresAt==100,"OP-15 own buff strength applies to initial60 while retaining original expiry");long end=early.expiresAt;check(b.UsePanzerTool(0,0) && early.expiresAt==end+100 && b.JobState(0).ToolUses[0]==2,"OP-13 panzer tool extends currently active fixed-turn oopart buff");ready(b,0);end=early.expiresAt;check(b.UsePanzerTool(0,0) && early.expiresAt==end+100 && b.JobState(0).ToolUses[0]==1,"OP-13 repeated extension stacks without a shared extension cap");b.State.Heroes[0].TakeDamage(b.State.Heroes[0].HitPoints);check(b.RequiresPanzerDefense(0) && !b.CanUsePanzerTool(0,0,1),"OP-12 armor break retains tool constraints");b.State.Heroes[0].TryArmorCall(b.State.Heroes[0].ArmorCallAt);check(b.JobState(0).ToolUses[0]==1,"OP-12 armor return never refills used tool counts");
        var decay=new BuffInstance{sourceActorId="a",sourceId="decay",kind="attack",initialValue=72,value=72,decayAmount=10,nextDecayAt=100,expiresAt=300};check(decay.Extend(50,100),"OP-13 active decay buff may be extended");decay.Tick(100);check(decay.value==62 && decay.decayAmount==10 && decay.nextDecayAt==200,"OP-15 initial amplification never reduces decay amount or changes period");decay.Tick(200);check(decay.value==52,"OP-15 next boundary continues original ten-point decay");var expired=new BuffInstance{expiresAt=100,value=60};check(!expired.Extend(100,100) && expired.expired,"OP-14 same-timestamp expiry is processed before an extension");b.State.Heroes[1].ApplyOopartBuffs(new[]{new TimedSelfEffectDef{kind="speed",percent=20,turns=3}},"later.actor","later.buff",0);var after=b.State.Heroes[1].OopartBuffs.Single(v=>v.sourceId=="later.buff");check(after.expiresAt==b.Clock+300,"OP-14 a buff applied after two tool uses receives only its original duration");var unlimited=new BuffInstance{expiresAt=300,value=20};for(int i=0;i<20;i++)unlimited.Extend(50,100);check(unlimited.expiresAt==2300,"OP-13 repeated tool extension has no old ten-turn lifetime cap");var constant=new BuffInstance{expiresAt=300,value=20,extendable=false};check(!constant.Extend(10,100),"OP-14 nonextendable effects are ignored");
        save=fresh();ordinary=new PlayableBattle(50,new PlayableProgress(),1137,combatDefinitions:combat,formalGrowth:save.growth,useJobRulesV2:true);b=battle(save,combat,null);check(b.State.Heroes.Select(x=>new{x.MaxHitPoints,x.Attack,x.PhysicalDefense,x.MagicDefense,x.Speed}).SequenceEqual(ordinary.State.Heroes.Select(x=>new{x.MaxHitPoints,x.Attack,x.PhysicalDefense,x.MagicDefense,x.Speed})),"OP-16 owning all42 ooparts without equipment causes absolutely no party-wide stat bonus");
        var journal=new FormalCampaignJournal(save,encode,decode);var request=new OopartRequest("op.equip",journal.Revision,"equip",d.id);string before=encode(journal.Snapshot);check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>false,home)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"OP-17 failed equip save publishes nothing");reject(()=>journal.CommitOopart(new OopartRequest("op.other",journal.Revision,"equip",d.id),catalog,combat.FormationIds,s=>true,home),"OP-17 frozen operation blocks a different retry");check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>true,home)==GrowthCommitResult.Committed,"OP-17 retry commits one equip operation");check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>throw new Exception(),home)==GrowthCommitResult.AlreadyCommitted,"OP-17 completed equip replay does not write or mutate");journal.LockOopartsForBattle();reject(()=>journal.CommitOopart(new OopartRequest("op.inbattle",journal.Revision,"equip",null),catalog,combat.FormationIds,s=>true,home),"OP-17 equipment cannot change during battle");journal.UnlockOopartsAfterBattle();request=new OopartRequest("op.level",journal.Revision,"level",d.id,count:10);before=encode(journal.Snapshot);check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>false,home)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"OP-17 failed ten-level upgrade consumes no materials");check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>true,home)==GrowthCommitResult.Committed && journal.Snapshot.collection.ooparts.progress.Single(x=>x.oopartId==d.id).level==11,"OP-17 ten-level retry applies once");
        var snap=journal.Snapshot;var random=snap.collection.ooparts.progress.Single(x=>x.oopartId==d.id);random.accumulatedRandomStats.attack=80;random.accumulatedRandomStats.hp=320;random.accumulatedRandomStats.speed=10;journal=new FormalCampaignJournal(snap,encode,decode);request=new OopartRequest("op.direct",journal.Revision,"direct",d.id,stat:"attack");before=encode(journal.Snapshot);check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>false,home)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"OP-17 failed rescue upgrade consumes neither50,000 nectar nor20 high-level materials");int nectar=journal.Snapshot.growth.nectar,mat=HomeRules.Balance(journal.Snapshot,d.directMaterialId);check(journal.CommitOopart(request,catalog,combat.FormationIds,s=>true,home)==GrowthCommitResult.Committed && journal.Snapshot.growth.nectar==nectar-50000 && HomeRules.Balance(journal.Snapshot,d.directMaterialId)==mat-20 && journal.Snapshot.collection.ooparts.progress.Single(x=>x.oopartId==d.id).accumulatedRandomStats.attack==85,"OP-17 successful rescue retry costs exactly once and adds five-percent maximum");
        save=fresh();var upgraded=save.collection.ooparts.progress.Single(x=>x.oopartId==d.id);upgraded.accumulatedRandomStats=new StatValues{hp=320,attack=80,physicalDefense=80,magicDefense=80,speed=10};
        foreach(string stat in StatValues.Names){int previous=upgraded.accumulatedRandomStats.Get(stat);OopartService.Direct(save,catalog,d.id,stat);check(upgraded.accumulatedRandomStats.Get(stat)>previous,"OP-17 direct upgrade independently increases "+stat);}
        int steps=OopartService.LevelUp(save,catalog,d.id,120);check(steps==119 && upgraded.level==120,"OP-17 MAX upgrades only remaining119 levels");reject(()=>OopartService.LevelUp(save,catalog,d.id,1),"OP-17 level cap consumes no further materials");
        var huntCatalog=catalog.Copy();string colossus=WorldCatalog.ColossusIds[0];foreach(var band in huntCatalog.rewardBands.Where(x=>x.ownerId==colossus))band.relicIds=new[]{d.id};int dropSeed=Enumerable.Range(0,100).First(seed=>new Random(seed^0x48554E54).Next(10000)<3500);
        save=fresh();save.collection.ooparts.progress.Single(x=>x.oopartId==d.id).level=7;OopartService.Equip(save.collection.ooparts,0,d.id);journal=new FormalCampaignJournal(save,encode,decode);
        var session=new BattleCollectionSession(huntCatalog,"op.drop",colossus,20,0,combat.FormationIds,dropSeed,relicHunt:true);var endRequest=new FormalBattleEndRequest(session.Finish(BattleEndReason.Victory,save.world.poemIds,save.world.unlockedStoryIds),0);
        Func<CampaignSaveV2,CampaignSaveV2> victory=w=>{var state=new CampaignState(WorldCatalog.ColossusIds,w);state.ClaimColossusVictory(colossus,WorldCatalog.Colossi[0].EnvironmentTags,new VictoryReward(endRequest.Id,20,10,4,Array.Empty<string>()),Array.Empty<StoryRequirement>(),Array.Empty<TerraformingMilestone>(),GardenCatalog.Requirements);return state.CreateSave();};
        before=encode(journal.Snapshot);check(journal.CommitBattleEnd(endRequest,huntCatalog,victory,s=>false,home)==GrowthCommitResult.SaveFailed && encode(journal.Snapshot)==before,"OP-01 battle drop save failure leaves all five rolls, equipment and inventory intact");
        check(journal.CommitBattleEnd(endRequest,huntCatalog,victory,s=>true,home)==GrowthCommitResult.Committed,"OP-01 battle drop retry saves frozen random acquisition");
        var acquired=journal.Snapshot.collection.receipts.Single().relicDrops.First();var retained=journal.Snapshot.collection.ooparts.progress.Single(x=>x.oopartId==d.id);
        check(acquired.randomStats!=null && acquired.previousRandomStats!=null && acquired.resultRandomStats!=null && retained.level==7 && journal.Snapshot.collection.ooparts.slots[0].equippedOopartId==d.id,"OP-01 acquisition receipt includes five-stat before/after and preserves upgraded equipment");
        check(StatValues.Names.All(k=>acquired.resultRandomStats.Get(k)==Math.Max(acquired.previousRandomStats.Get(k),acquired.randomStats.Get(k))),"OP-02 live battle acquisition keeps independent component maxima");
        check(journal.CommitBattleEnd(endRequest,huntCatalog,victory,s=>throw new Exception(),home)==GrowthCommitResult.AlreadyCommitted,"OP-17 replay cannot grant or roll battle drops twice");
        var old=fresh();old.collection.ooparts=null;old.collection.relics=new[]{new CollectionRelic{id=d.id,contentVersion=catalog.contentVersion,level=120,attackRoll=80,hpRoll=800}};old.collection.equipment=new[]{new CollectionEquipment{heroineId=combat.FormationIds[0],relicId=d.id}};string oldEquipment=JsonSerializer.Serialize(old.collection.equipment,json);OopartSaveAdapter.Migrate(old.collection,catalog,combat.FormationIds);check(old.collection.ooparts.progress.Single().level==120 && old.collection.ooparts.progress.Single().accumulatedRandomStats.hp==800 && old.collection.ooparts.progress.Single().legacyHpMaximum==1000 && old.collection.ooparts.slots[0].equippedOopartId==d.id && JsonSerializer.Serialize(old.collection.equipment,json)==oldEquipment,"OP-18 old collection, level, rolls and owner-equipment archive survive migration");before=encode(old);OopartSaveAdapter.Migrate(old.collection,catalog,combat.FormationIds);check(encode(old)==before && decode(before).collection.ooparts.progress.Single().accumulatedRandomStats.hp==800,"OP-18 migration is idempotent and serializable");
        Console.WriteLine("PLAN14_OOPART_PASS OP-01..OP-18 / five independent stats / slot presets / atomic save / buffs / jobs / legacy");
    }
}
