using System;
using System.IO;
using System.Linq;
using System.Text.Json;
using NewAster.Core;
using NewAster.Data;
internal static class Plan10ShellTests
{
    public static void Run(Action<bool,string> check,string resources)
    {
        var options=new JsonSerializerOptions{IncludeFields=true};
        Func<CombatDefinitionCatalog> read=()=>JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-shell.json")),options);
        var c=read();c.Validate();var old=JsonSerializer.Deserialize<CombatDefinitionCatalog>(File.ReadAllText(Path.Combine(resources,"Combat/battle-plan10-annihilator.json")),options);
        check(c.HeroineIds.Length==9 && c.HeroineIds.Select(c.PersonId).Distinct().Count()==8 && c.jobs.Length==8,"Shell supplies ninth form, eighth person and eighth job");
        foreach(var h in old.heroines){check(JsonSerializer.Serialize(h,options)==JsonSerializer.Serialize(c.Hero(h.id),options),"Previous heroine unchanged: "+h.id);foreach(var id in h.skills)check(JsonSerializer.Serialize(old.skills.Single(s=>s.id==id),options)==JsonSerializer.Serialize(c.skills.Single(s=>s.id==id),options),"Previous skill unchanged: "+id);}
        var growth=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=4321,stones=1234,heroines=c.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=20}).ToArray()};
        Func<int,PanzerLoadout,PlayableBattle> fixture=(slot,loadout)=>{var defs=read();foreach(var j in defs.jobs)j.hp=100000;var ids=defs.FormationIds;ids[slot]="heroine.shell";var enemy=ColossusCombatCatalog.Get(WorldCatalog.ColossusIds[0]);enemy.baseHp=10000000;enemy.hpPerLevel=1;return new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:defs.WithFormation(ids),formalGrowth:growth,colossusDefinition:enemy,useJobRulesV2:true,panzerLoadout:loadout);};
        Action<PlayableBattle,int> ready=(b,a)=>{int limit=0;while(b.AvailableHero!=a && !b.Ended && limit++<500){int current=b.AvailableHero;if(b.RequiresPanzerDefense(current))b.DefendPanzer(current);else b.Pass();}check(!b.Ended && b.AvailableHero==a,"Panzer reaches own READY");};
        foreach(int slot in Enumerable.Range(0,5)){var b=fixture(slot,null);ready(b,slot);check(b.JobState(slot).Id=="job.panzer" && b.State.Heroes[slot].ArmorActive,"Panzer follows ID in every formation slot");}
        bool rejected=false;try{new PanzerLoadout("physical","repair","repair");}catch(ArgumentException){rejected=true;}check(rejected,"Duplicate setup tools rejected before battle");
        var armor=fixture(0,null);ready(armor,0);var hero=armor.State.Heroes[0];int full=hero.HitPoints;hero.TakeDamage(1000);int hurt=hero.HitPoints;hero.Heal(10000);check(hero.HitPoints==hurt,"Ordinary healing cannot repair armor");
        check(armor.CanUsePanzerTool(0,0,0) && armor.UsePanzerTool(0,0) && hero.HitPoints>hurt && armor.JobState(0).ToolUses[0]==1,"Repair uses its finite charge");ready(armor,0);hero.TakeDamage(1000);check(armor.UsePanzerTool(0,0) && armor.JobState(0).ToolUses[0]==0,"Second repair exhausts slot");ready(armor,0);long before=armor.Clock;check(!armor.UsePanzerTool(0,0) && armor.Clock==before,"Exhausted tool rejects without advancing time");
        hero.TakeDamage(int.MaxValue);long broken=armor.Clock;check(!hero.ArmorActive && hero.HitPoints==hero.FleshMaxHitPoints && hero.ArmorCallAt==broken+300 && full>=hero.FleshMaxHitPoints*15,"Break enters living one-fifth flesh with exact call deadline");
        int hp=hero.HitPoints;hero.TakeDamage(100);hero.Heal(50);check(hero.HitPoints==hp-50,"Ordinary healing reaches flesh");
        int flesh=hero.HitPoints;before=armor.Clock;armor.Pass();check(armor.Clock==before && !armor.Act(0,0,"body") && !armor.UsePanzerTool(0,1),"Flesh rejects pass skills and tools atomically");
        check(armor.DefendPanzer(0),"Flesh can defend");int guard=0;while(!hero.ArmorActive && !armor.Ended && guard++<500){int a=armor.AvailableHero;if(armor.RequiresPanzerDefense(a))armor.DefendPanzer(a);else armor.Pass();}
        check(hero.ArmorActive && hero.FleshHitPoints<=flesh && armor.JobState(0).ToolUses[0]==0 && armor.DrainPresentationEvents().Any(e=>e.Clock==broken+300 && e.Message.Contains("ARMOR CALL")),"Armor call occurs at Clock300, retains flesh wounds and never refills tools");
        hero.TakeDamage(int.MaxValue);check(!hero.ArmorActive && hero.HitPoints==hero.FleshHitPoints,"Second break retains flesh HP");hero.TakeDamage(int.MaxValue);before=armor.Clock;check(!hero.TryArmorCall(before+1000) && !hero.IsAlive,"Death prevents automatic armor revival");
        var fresh=fixture(0,null);check(fresh.JobState(0).ToolUses.SequenceEqual(new[]{2,2}) && fresh.State.Heroes[0].ArmorActive,"New encounter resets armor and finite tools");
        var healDefs=read();foreach(var j in healDefs.jobs)j.hp=100000;var healIds=healDefs.FormationIds;healIds[0]="heroine.shell";healIds[1]="heroine.annihilator-holy";var healing=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:healDefs.WithFormation(healIds),formalGrowth:growth,useJobRulesV2:true);ready(healing,1);healing.State.Heroes[1].GainResource(10);var panzer=healing.State.Heroes[0];panzer.TakeDamage(500);check(healing.PreviewHealing(1,0,0)==0 && !healing.CanUseLifeTool(1,"heal",0) && !healing.CanUseLifeTool(1,"overheal",0),"Healer previews and life tools reject armor targets");panzer.TakeDamage(int.MaxValue);panzer.TakeDamage(500);check(healing.PreviewHealing(1,0,0)>0 && healing.CanUseLifeTool(1,"heal",0),"Healer reaches the same person after armor break");
        var fire=fixture(0,new PanzerLoadout("fire","rally","extend"));ready(fire,0);fire.State.Heroes[0].AddStatus(new EnemyStatusDef{kind="burn",amount=100});check(!fire.State.Heroes[0].Status.Active("burn") && fire.State.Heroes[0].Status.Meter("burn")==50,"Fire lining halves burn accumulation while armored");
        var fireDefs=read();var fireIds=fireDefs.FormationIds;fireIds[0]="heroine.shell";var fireEnemy=ProductionEconomyCatalog.Enemy("colossus.black-smoke-citadel");foreach(var action in fireEnemy.actionCycle)action.damageType="physical";var fireArmor=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:fireDefs.WithFormation(fireIds),formalGrowth:growth,colossusDefinition:fireEnemy,useJobRulesV2:true,panzerLoadout:new PanzerLoadout("fire"));var magicArmor=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:fireDefs.WithFormation(fireIds),formalGrowth:growth,colossusDefinition:fireEnemy,useJobRulesV2:true,panzerLoadout:new PanzerLoadout("magic"));check(fireArmor.PreviewEnemyDamage(0)<magicArmor.PreviewEnemyDamage(0) && fireEnemy.Copy().majorAttributes.Contains("火"),"Element armor reduces tagged fire damage and cloned enemy retains attributes");
        check(fire.UsePanzerTool(0,0,2) && fire.State.Heroes[2].TimedEffects.Any(e=>e.Kind=="attack" && e.Percent==25),"Rally buffs selected ally");ready(fire,0);check(fire.UsePanzerTool(0,1) && fire.JobState(0).ToolUses[1]==1,"Second loadout tool extends active ally effects");
        var attack=fixture(0,null);ready(attack,0);int normal=attack.PreviewDamage(0,2,"body"),partNormal=attack.PreviewDamage(0,2,attack.State.Parts[0].Id);attack.State.BossStatus.Add(new EnemyStatusDef{kind="burn",amount=1000});check(attack.PreviewDamage(0,2,"body")>normal,"Shell ultimate gains damage against the selected burning target");check(attack.PreviewDamage(0,2,attack.State.Parts[0].Id)==partNormal,"Burn on body never grants bonus against a different part");
        check(attack.Act(0,1,"body") && attack.State.BossStatus.Active("burn"),"Fire strike executes as a physical skill");
        Console.WriteLine("PLAN10_SHELL_COMBAT_PASS armor / defense / call / tools / skill synergy");
        if(Environment.GetEnvironmentVariable("NEWASTER_PLAN10_SHELL_ART")!="1")return;
        var story=JsonSerializer.Deserialize<ProductionStoryContent>(File.ReadAllText(Path.Combine(resources,"Story/plan10-shell-story-content.json")),options);story.Validate(c.HeroineIds,WorldCatalog.ColossusIds.ToArray());var home=ProductionStoryCatalog.Home(c,story);home.Validate(true);var collection=ProductionStoryCatalog.Collection(c,story);
        check(home.weaponNodes.Count(n=>n.heroineId=="heroine.shell")==13 && home.assets.All(a=>!a.placeholder),"Shell has thirteen weapon nodes and adopted dedicated art");check(story.chapters.Where(x=>x.ownerId=="heroine.shell").Sum(x=>x.pages.Length)==30 && story.events.Count(e=>e.ownerId=="heroine.shell")==5,"Shell has thirty pages and five relationship events");
        var priorGrowth=new FormalGrowthSave{saveId="newaster.formal-growth",nectar=4321,stones=1234,heroines=old.HeroineIds.Select(id=>new FormalHeroineGrowth{heroineId=id,level=20}).ToArray()};var save=new FormalCampaignSave{growth=priorGrowth,world=new CampaignState(WorldCatalog.ColossusIds).CreateSave(),home=FormalHomeProgress.Empty(home.contentVersion),collection=new FormalCollectionLedger{contentVersion=collection.contentVersion}};HomeConditions.Refresh(save,home);save.Validate();save.home.ValidateContent(home,save);
        var p=new FormalProgression(priorGrowth,c.HeroineIds);var request=new GrowthRequest("shell-free","heroine.shell",priorGrowth.revision,GrowthOperation.ReceiveHeroine);check(p.Commit(request,s=>false)==GrowthCommitResult.SaveFailed && p.Snapshot.heroines.Length==8,"Failed recruitment leaves existing eight forms intact");check(p.Commit(request,s=>true)==GrowthCommitResult.Committed && p.Commit(request,s=>false)==GrowthCommitResult.AlreadyCommitted && p.Snapshot.nectar==4321 && p.Snapshot.stones==1234,"Free recruitment persists once and preserves balances");
        save.growth=p.Snapshot;HomeConditions.Refresh(save,home);var operation=new HomeOperation("panzer-loadout","heroine.shell","magic","rally","extend");Func<FormalCampaignSave,FormalCampaignSave> clone=s=>JsonSerializer.Deserialize<FormalCampaignSave>(JsonSerializer.Serialize(s,options),options);var journal=new FormalCampaignJournal(save,s=>JsonSerializer.Serialize(s,options),s=>JsonSerializer.Deserialize<FormalCampaignSave>(s,options));var setupRequest=new FormalHomeRequest("shell-setup","panzer-loadout",save.revision,home.contentVersion,operation.Key);check(journal.CommitHomeOperation(setupRequest,home,operation,s=>false)==GrowthCommitResult.SaveFailed && journal.Snapshot.home.panzerEquipment.Length==0,"Setup failure preserves old loadout");check(journal.CommitHomeOperation(setupRequest,home,operation,s=>true)==GrowthCommitResult.Committed && journal.CommitHomeOperation(setupRequest,home,operation,s=>false)==GrowthCommitResult.AlreadyCommitted,"Setup retry saves once");var restored=clone(journal.Snapshot);restored.Validate();restored.home.ValidateContent(home,restored);check(restored.home.panzerEquipment.Single().resistance=="magic" && restored.home.panzerEquipment.Single().firstTool=="rally" && restored.growth.nectar==4321,"Armor and tool selections round-trip independently of balances");
        var equipped=clone(restored);equipped.home.weaponNodeIds=equipped.home.weaponNodeIds.Union(new[]{"heroine.shell.weapon.alpha"}).ToArray();equipped.home.weaponEquipment=new[]{new HomeWeaponEquipment{heroineId="heroine.shell",nodeId="heroine.shell.weapon.alpha"}};var equipIds=new[]{"heroine.shell"}.Concat(c.FormationIds.Skip(1)).ToArray();var plain=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:c.WithFormation(equipIds),formalGrowth:restored.growth,homeProgress:restored.home,homeCatalog:home,useJobRulesV2:true);var armed=new PlayableBattle(1,new PlayableProgress(),991,combatDefinitions:c.WithFormation(equipIds),formalGrowth:equipped.growth,homeProgress:equipped.home,homeCatalog:home,useJobRulesV2:true);ready(plain,0);ready(armed,0);check(armed.PreviewDamage(0,0,"body")>plain.PreviewDamage(0,0,"body") && armed.SkillName(0,0)=="コンバット・フッキング","Shell weapon strengthens her own skill without replacing its name");
        Console.WriteLine("PLAN10_SHELL_CONTENT_PASS compatible saves / growth / story / art");
    }
}
